In [16]:
import os

files = [
    f for f in os.listdir()
    if f.lower().endswith(".xlsx")
    and f.startswith("Ringkasan Broker")
]

print("Jumlah file:", len(files))

for f in sorted(files):
    print(f)

Jumlah file: 29
Ringkasan Broker-20260824.xlsx
Ringkasan Broker-20260826.xlsx
Ringkasan Broker-20260827.xlsx
Ringkasan Broker-20260828.xlsx
Ringkasan Broker-20260831.xlsx
Ringkasan Broker-20260901.xlsx
Ringkasan Broker-20260902.xlsx
Ringkasan Broker-20260903.xlsx
Ringkasan Broker-20260904.xlsx
Ringkasan Broker-20260907.xlsx
Ringkasan Broker-20260908.xlsx
Ringkasan Broker-20260909.xlsx
Ringkasan Broker-20260910.xlsx
Ringkasan Broker-20260911.xlsx
Ringkasan Broker-20260914.xlsx
Ringkasan Broker-20260915.xlsx
Ringkasan Broker-20260916.xlsx
Ringkasan Broker-20260917.xlsx
Ringkasan Broker-20260918.xlsx
Ringkasan Broker-20260921.xlsx
Ringkasan Broker-20260922.xlsx
Ringkasan Broker-20260923.xlsx
Ringkasan Broker-20260924.xlsx
Ringkasan Broker-20260925.xlsx
Ringkasan Broker-20260928.xlsx
Ringkasan Broker-20260929.xlsx
Ringkasan Broker-20260930.xlsx
Ringkasan Broker-20261001.xlsx
Ringkasan Broker-20261002 (4).xlsx

In [17]:
import pandas as pd
import os
import re

# =========================================================
# 1. Ambil semua file Ringkasan Broker
# =========================================================

files = sorted([
    f for f in os.listdir()
    if f.lower().endswith(".xlsx")
    and f.startswith("Ringkasan Broker")
])

print("Jumlah file ditemukan:", len(files))

# =========================================================
# 2. Baca dan gabungkan semua file
# =========================================================

all_data = []

for file in files:
    temp = pd.read_excel(file)

    # Ambil tanggal 8 digit dari nama file
    match = re.search(r"(\d{8})", file)

    if match:
        temp["Date"] = match.group(1)
    else:
        temp["Date"] = None

    all_data.append(temp)

df_all = pd.concat(all_data, ignore_index=True)

# =========================================================
# 3. Cleaning
# =========================================================

df_clean = df_all.copy()

# Rapikan nama kolom
df_clean.columns = df_clean.columns.str.strip()

# Rapikan kolom teks
df_clean["Kode Perusahaan"] = (
    df_clean["Kode Perusahaan"]
    .astype(str)
    .str.strip()
    .str.upper()
)

df_clean["Nama Perusahaan"] = (
    df_clean["Nama Perusahaan"]
    .astype(str)
    .str.strip()
)

# Rapikan tanggal
df_clean["Date"] = (
    df_clean["Date"]
    .astype(str)
    .str.extract(r"(\d{8})")[0]
)

# Kolom numerik
numeric_cols = ["Volume", "Nilai", "Frekuensi"]

for col in numeric_cols:
    df_clean[col] = (
        df_clean[col]
        .astype(str)
        .str.replace(",", "", regex=False)
    )

    df_clean[col] = pd.to_numeric(
        df_clean[col],
        errors="coerce"
    )

# Urutkan data
df_clean = df_clean.sort_values(
    ["Date", "Kode Perusahaan"]
).reset_index(drop=True)

# =========================================================
# 4. Pemeriksaan dataset
# =========================================================

print("\n===== DATASET CHECK =====")

print("Jumlah file :", len(files))
print("Jumlah baris:", len(df_clean))
print("Jumlah broker unik:", df_clean["Kode Perusahaan"].nunique())

print("\nTanggal:")
print(sorted(df_clean["Date"].dropna().unique()))

print("\nMissing value:")
print(df_clean.isna().sum())

print("\nDuplikat Date + Kode Broker:")
print(
    df_clean.duplicated(
        subset=["Date", "Kode Perusahaan"]
    ).sum()
)

print("\n5 baris pertama:")
display(df_clean.head())

Jumlah file ditemukan: 29

===== DATASET CHECK =====
Jumlah file : 29
Jumlah baris: 2552
Jumlah broker unik: 88

Tanggal:
['20260824', '20260826', '20260827', '20260828', '20260831', '20260901', '20260902', '20260903', '20260904', '20260907', '20260908', '20260909', '20260910', '20260911', '20260914', '20260915', '20260916', '20260917', '20260918', '20260921', '20260922', '20260923', '20260924', '20260925', '20260928', '20260929', '20260930', '20261001', '20261002']

Missing value:
No                 0
Kode Perusahaan    0
Nama Perusahaan    0
Volume             0
Nilai              0
Frekuensi          0
Date               0
dtype: int64

Duplikat Date + Kode Broker:
0

5 baris pertama:

,No,Kode Perusahaan,Nama Perusahaan,Volume,Nilai,Frekuensi,Date
0,1,AD,Sukadana Prima Sekuritas,4142700,1443620900,267,20260824
1,2,AF,Harita Kencana Sekuritas,6224200,5029717500,463,20260824
2,3,AG,Kiwoom Sekuritas Indonesia,581185700,168137959000,32613,20260824
3,4,AH,Shinhan Sekuritas Indonesia,1409100,407006900,81,20260824
4,5,AI,Kay Hian Sekuritas,310831700,147304751400,14172,20260824

In [18]:
# =========================================================
# TIER 1 — KISI MARKET POSITION
# 29 TRADING DAYS
# =========================================================

# ---------------------------------------------------------
# 1. RANKING & MARKET SHARE HARIAN
# ---------------------------------------------------------

# Ranking berdasarkan nilai transaksi setiap hari
df_clean["Rank_Nilai"] = (
    df_clean.groupby("Date")["Nilai"]
    .rank(method="min", ascending=False)
)

# Total nilai transaksi seluruh broker setiap hari
df_clean["Total_Nilai_Harian"] = (
    df_clean.groupby("Date")["Nilai"]
    .transform("sum")
)

# Market share setiap broker setiap hari
df_clean["Market_Share"] = (
    df_clean["Nilai"]
    / df_clean["Total_Nilai_Harian"]
    * 100
)


# ---------------------------------------------------------
# 2. KISI DAILY DATA
# ---------------------------------------------------------

kisi_daily = (
    df_clean[df_clean["Kode Perusahaan"] == "BQ"]
    [[
        "Date",
        "Kode Perusahaan",
        "Nama Perusahaan",
        "Nilai",
        "Volume",
        "Frekuensi",
        "Rank_Nilai",
        "Market_Share"
    ]]
    .sort_values("Date")
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 3. SUMMARY SEMUA BROKER — 29 TRADING DAYS
# ---------------------------------------------------------

broker_summary_29d = (
    df_clean.groupby(
        ["Kode Perusahaan", "Nama Perusahaan"],
        as_index=False
    )
    .agg(
        Avg_Nilai=("Nilai", "mean"),
        Avg_Volume=("Volume", "mean"),
        Avg_Frekuensi=("Frekuensi", "mean"),
        Avg_Market_Share=("Market_Share", "mean"),
        Avg_Rank=("Rank_Nilai", "mean")
    )
    .sort_values("Avg_Nilai", ascending=False)
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 4. KISI SUMMARY
# ---------------------------------------------------------

kisi_summary = broker_summary_29d[
    broker_summary_29d["Kode Perusahaan"] == "BQ"
].copy()

print("========== KISI SUMMARY — 29 TRADING DAYS ==========")
display(kisi_summary)


# ---------------------------------------------------------
# 5. KISI BEST & WORST PERFORMANCE
# ---------------------------------------------------------

best_rank_row = kisi_daily.loc[
    kisi_daily["Rank_Nilai"].idxmin()
]

worst_rank_row = kisi_daily.loc[
    kisi_daily["Rank_Nilai"].idxmax()
]

highest_ms_row = kisi_daily.loc[
    kisi_daily["Market_Share"].idxmax()
]

lowest_ms_row = kisi_daily.loc[
    kisi_daily["Market_Share"].idxmin()
]

print("========== KISI DAILY EXTREMES ==========")

print(
    f"Best Rank       : #{int(best_rank_row['Rank_Nilai'])} "
    f"on {best_rank_row['Date']}"
)

print(
    f"Worst Rank      : #{int(worst_rank_row['Rank_Nilai'])} "
    f"on {worst_rank_row['Date']}"
)

print(
    f"Highest Mkt Share: {highest_ms_row['Market_Share']:.3f}% "
    f"on {highest_ms_row['Date']}"
)

print(
    f"Lowest Mkt Share : {lowest_ms_row['Market_Share']:.3f}% "
    f"on {lowest_ms_row['Date']}"
)


# ---------------------------------------------------------
# 6. SELECTED COMPETITORS
# ---------------------------------------------------------

selected_codes = ["BQ", "XL", "CC", "YP", "PD", "XC"]

tier1_comparison_29d = broker_summary_29d[
    broker_summary_29d["Kode Perusahaan"].isin(selected_codes)
].copy()


# ---------------------------------------------------------
# 7. VALUE DALAM RP TRILIUN
# ---------------------------------------------------------

tier1_comparison_29d["Avg_Nilai_Trillion"] = (
    tier1_comparison_29d["Avg_Nilai"] / 1e12
)


# ---------------------------------------------------------
# 8. GAP VS KISI
# ---------------------------------------------------------

kisi_baseline = tier1_comparison_29d[
    tier1_comparison_29d["Kode Perusahaan"] == "BQ"
].iloc[0]

tier1_comparison_29d["Value_vs_KISI_x"] = (
    tier1_comparison_29d["Avg_Nilai"]
    / kisi_baseline["Avg_Nilai"]
)

tier1_comparison_29d["Market_Share_Gap_pp"] = (
    tier1_comparison_29d["Avg_Market_Share"]
    - kisi_baseline["Avg_Market_Share"]
)

tier1_comparison_29d["Rank_Gap_vs_KISI"] = (
    tier1_comparison_29d["Avg_Rank"]
    - kisi_baseline["Avg_Rank"]
)


# ---------------------------------------------------------
# 9. TABEL FINAL UNTUK PPT
# ---------------------------------------------------------

tier1_ppt = tier1_comparison_29d[[
    "Kode Perusahaan",
    "Nama Perusahaan",
    "Avg_Nilai_Trillion",
    "Avg_Market_Share",
    "Avg_Rank",
    "Avg_Frekuensi",
    "Value_vs_KISI_x",
    "Market_Share_Gap_pp"
]].sort_values(
    "Avg_Nilai_Trillion",
    ascending=False
)

print("\n========== FINAL TIER 1 TABLE ==========")

display(
    tier1_ppt.style.format({
        "Avg_Nilai_Trillion": "{:.3f}",
        "Avg_Market_Share": "{:.3f}%",
        "Avg_Rank": "{:.1f}",
        "Avg_Frekuensi": "{:,.0f}",
        "Value_vs_KISI_x": "{:.2f}x",
        "Market_Share_Gap_pp": "{:+.3f}"
    })
)

========== KISI SUMMARY — 29 TRADING DAYS ==========

,Kode Perusahaan,Nama Perusahaan,Avg_Nilai,Avg_Volume,Avg_Frekuensi,Avg_Market_Share,Avg_Rank
23,BQ,Korea Investment and Sekuritas Indonesia,2.826132e+11,1.187159e+09,58355.172414,0.934142,24.137931

========== KISI DAILY EXTREMES ==========
Best Rank       : #18 on 20260910
Worst Rank      : #31 on 20260930
Highest Mkt Share: 1.510% on 20260910
Lowest Mkt Share : 0.584% on 20260930

========== FINAL TIER 1 TABLE ==========

In [19]:
avg_frequency = (
    df.groupby(["Kode Perusahaan", "Nama Perusahaan"])["Frekuensi"]
      .mean()
      .reset_index()
      .rename(columns={"Frekuensi": "Avg_Frekuensi"})
      .sort_values("Avg_Frekuensi", ascending=False)
)

avg_frequency

   Kode Perusahaan                  Nama Perusahaan  Avg_Frekuensi
80              XL       Stockbit Sekuritas Digital       861811.0
17              CC                MANDIRI SEKURITAS       281275.0
5               AK          UBS Sekuritas Indonesia       204679.0
84              YP  Mirae Asset Sekuritas Indonesia       184127.0
79              XC             Ajaib Sekuritas Asia       165198.0
..             ...                              ...            ...
32              GA          BNC Sekuritas Indonesia          160.0
41              II        Danatama Makmur Sekuritas          104.0
43              IT           INTI TELADAN SEKURITAS           91.0
83              YO     Amantara Sekuritas Indonesia           79.0
12              BF            Inti Fikasa Sekuritas           24.0

[88 rows x 3 columns]

In [26]:
# =========================================================
# TIER 1 — AVG RANK UNTUK PPT
# =========================================================

avg_rank_ppt = (
    tier1_comparison_29d[
        [
            "Kode Perusahaan",
            "Nama Perusahaan",
            "Avg_Rank"
        ]
    ]
    .sort_values(
        "Avg_Rank",
        ascending=True
    )
    .reset_index(drop=True)
)

# Ranking kompetitif berdasarkan Avg Rank
avg_rank_ppt["Competitive_Rank"] = (
    avg_rank_ppt["Avg_Rank"]
    .rank(
        method="min",
        ascending=True
    )
    .astype(int)
)

# Urutkan berdasarkan Competitive Rank
avg_rank_ppt = (
    avg_rank_ppt
    .sort_values("Competitive_Rank")
    .reset_index(drop=True)
)

print("========== TIER 1 — AVG RANK ==========")

display(
    avg_rank_ppt.style.format({
        "Avg_Rank": "{:.1f}",
        "Competitive_Rank": "{:d}"
    })
)

========== TIER 1 — AVG RANK ==========

In [27]:
# =========================================================
# TIER 1 — AVERAGE VOLUME
# =========================================================

volume_ppt = (
    tier1_comparison_29d[
        [
            "Kode Perusahaan",
            "Nama Perusahaan",
            "Avg_Volume"
        ]
    ]
    .sort_values(
        "Avg_Volume",
        ascending=False
    )
    .reset_index(drop=True)
)

print("========== TIER 1 — AVERAGE VOLUME ==========")

display(
    volume_ppt.style.format({
        "Avg_Volume": "{:,.0f}"
    })
)

========== TIER 1 — AVERAGE VOLUME ==========

In [28]:
# ============================================================
# COMPETITIVE RANK — DAILY RANKING BASED ON MARKET SHARE
# ============================================================

import pandas as pd

# Pastikan Date bertipe datetime
df['Date'] = pd.to_datetime(df['Date'])

# Hitung total transaction value per hari
daily_total = (
    df.groupby('Date')['Transaction_Value']
      .sum()
      .reset_index(name='Total_Market_Value')
)

# Gabungkan total market value ke dataset
df_rank = df.merge(daily_total, on='Date', how='left')

# Hitung Market Share masing-masing perusahaan per hari
df_rank['Market_Share'] = (
    df_rank['Transaction_Value'] / df_rank['Total_Market_Value']
) * 100

# Ranking perusahaan setiap hari berdasarkan Market Share
# Rank 1 = Market Share terbesar
df_rank['Daily_Rank'] = (
    df_rank.groupby('Date')['Market_Share']
           .rank(method='min', ascending=False)
)

df_rank.head()

KeyError: 'Date'

In [29]:
print(df.columns.tolist())

['No', 'Kode Perusahaan', 'Nama Perusahaan', 'Volume', 'Nilai', 'Frekuensi']

In [30]:
# ============================================================
# COMPETITIVE RANK
# Ranking berdasarkan Nilai, Volume, dan Frekuensi
# ============================================================

# Pastikan data numerik
df['Volume'] = pd.to_numeric(df['Volume'], errors='coerce')
df['Nilai'] = pd.to_numeric(df['Nilai'], errors='coerce')
df['Frekuensi'] = pd.to_numeric(df['Frekuensi'], errors='coerce')

# Ranking masing-masing indikator
# Rank 1 = nilai tertinggi
df['Rank_Nilai'] = df['Nilai'].rank(
    ascending=False,
    method='min'
)

df['Rank_Volume'] = df['Volume'].rank(
    ascending=False,
    method='min'
)

df['Rank_Frekuensi'] = df['Frekuensi'].rank(
    ascending=False,
    method='min'
)

# Average Rank
df['Avg_Rank'] = df[
    ['Rank_Nilai', 'Rank_Volume', 'Rank_Frekuensi']
].mean(axis=1)

# Urutkan dari competitive position terbaik
competitive_rank = df.sort_values(
    'Avg_Rank',
    ascending=True
).reset_index(drop=True)

# Tampilkan hasil
competitive_rank[
    [
        'Kode Perusahaan',
        'Nama Perusahaan',
        'Nilai',
        'Volume',
        'Frekuensi',
        'Rank_Nilai',
        'Rank_Volume',
        'Rank_Frekuensi',
        'Avg_Rank'
    ]
]

,Kode Perusahaan,Nama Perusahaan,Nilai,Volume,Frekuensi,Rank_Nilai,Rank_Volume,Rank_Frekuensi,Avg_Rank
0,XL,Stockbit Sekuritas Digital,2420664239986,16737583022,861811,2.0,5.0,1.0,2.666667
1,AK,UBS Sekuritas Indonesia,2753551848888,19750284110,204679,1.0,4.0,3.0,2.666667
2,CC,MANDIRI SEKURITAS,1934335864396,10691047934,281275,4.0,7.0,2.0,4.333333
3,ZP,Maybank Sekuritas Indonesia,1836562596870,26479721482,115690,5.0,3.0,7.0,5.000000
4,YU,CGS International Sekuritas Indonesia,1969297578442,28079682880,83456,3.0,2.0,11.0,5.333333
...,...,...,...,...,...,...,...,...,...
83,RS,Yulie Sekuritas Indonesia Tbk.,1632580500,3626400,205,83.0,84.0,82.0,83.000000
84,PP,Aldiracita Sekuritas Indonesia,1541722500,582600,190,84.0,87.0,83.0,84.666667
85,IT,INTI TELADAN SEKURITAS,976952500,3375500,91,85.0,85.0,86.0,85.333333
86,YO,Amantara Sekuritas Indonesia,136060000,2160000,79,88.0,86.0,87.0,87.000000
87,BF,Inti Fikasa Sekuritas,246550000,300000,24,86.0,88.0,88.0,87.333333

In [31]:
competitive_rank.head(10)

,No,Kode Perusahaan,Nama Perusahaan,Volume,Nilai,Frekuensi,Rank_Nilai,Rank_Volume,Rank_Frekuensi,Avg_Rank
0,81,XL,Stockbit Sekuritas Digital,16737583022,2420664239986,861811,2.0,5.0,1.0,2.666667
1,6,AK,UBS Sekuritas Indonesia,19750284110,2753551848888,204679,1.0,4.0,3.0,2.666667
2,18,CC,MANDIRI SEKURITAS,10691047934,1934335864396,281275,4.0,7.0,2.0,4.333333
3,87,ZP,Maybank Sekuritas Indonesia,26479721482,1836562596870,115690,5.0,3.0,7.0,5.000000
4,86,YU,CGS International Sekuritas Indonesia,28079682880,1969297578442,83456,3.0,2.0,11.0,5.333333
5,51,MG,Semesta Indovest Sekuritas,46584962000,1651438460800,90094,6.0,1.0,10.0,5.666667
6,85,YP,Mirae Asset Sekuritas Indonesia,5799778706,1018579426900,184127,8.0,10.0,4.0,7.333333
7,14,BK,J.P. Morgan Sekuritas Indonesia,7411278680,1046776804128,78164,7.0,8.0,12.0,9.000000
8,20,CP,KB Valbury Sekuritas,6922842175,589531176850,98713,10.0,9.0,9.0,9.333333
9,80,XC,Ajaib Sekuritas Asia,2594737800,562905299000,165198,11.0,21.0,5.0,12.333333

In [32]:
df.loc[
    df["Kode Perusahaan"].eq("BQ"),
    [
        "Kode Perusahaan", "Nama Perusahaan",
        "Rank_Nilai", "Rank_Volume",
        "Rank_Frekuensi", "Avg_Rank"
    ]
]

,Kode Perusahaan,Nama Perusahaan,Rank_Nilai,Rank_Volume,Rank_Frekuensi,Avg_Rank
14,BQ,Korea Investment and Sekuritas Indonesia,29.0,32.0,18.0,26.333333

In [33]:
%pip install google-play-scraper pandas openpyxl

Collecting google-play-scraper
  Obtaining dependency information for google-play-scraper from https://files.pythonhosted.org/packages/33/f7/a23ef3cf8efc9ab3aee565971f59906811e6ce95475314ef7b18d02f30ba/google_play_scraper-1.2.7-py3-none-any.whl.metadata
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ---------------------------------------- 0.0/50.2 kB ? eta -:--:--
     -------- ------------------------------- 10.2/50.2 kB ? eta -:--:--
     ----------------------- -------------- 30.7/50.2 kB 262.6 kB/s eta 0:00:01
     ----------------------- -------------- 30.7/50.2 kB 262.6 kB/s eta 0:00:01
     ----------------------- -------------- 30.7/50.2 kB 262.6 kB/s eta 0:00:01
     ----------------------- -------------- 30.7/50.2 kB 262.6 kB/s eta 0:00:01
     ------------------------------ ------- 41.0/50.2 kB 122.9 kB/s eta 0:00:01
     -------------------------------------- 50.2/50.2 kB 142.4 kB/s eta 0:00:00
Requirement already satisfied: pandas in d:\anacondaupdate\lib\site-packages (2.2.3)
Requirement already satisfied: openpyxl in d:\anacondaupdate\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.23.2 in d:\anacondaupdate\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anacondaupdate\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anacondaupdate\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in d:\anacondaupdate\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: et-xmlfile in d:\anacondaupdate\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in d:\anacondaupdate\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7
Note: you may need to restart the kernel to use updated packages.

In [36]:
#GOOGLE APP STORE 

import re
import pandas as pd

from datetime import datetime
from zoneinfo import ZoneInfo
from google_play_scraper import reviews, Sort
from IPython.display import display

competitors = {
    "Ajaib": "ajaib.co.id",
    "Stockbit": "com.stockbit.android",
    "IPOT": "com.indopremier.ipot",
    "Mirae Asset (Neo HOTS)": "id.co.miraeassetdaewoo",
    "KISI (iKISI)": "com.koreainvestment.indonesia",
    "KISI (KOINS Mobile)": "com.koins.mtsand",
}

# Periode satu tahun sampai waktu kode dijalankan.
# Waktu ulasan dari scraper digunakan sebagaimana dikembalikan.
end_date = datetime.now(ZoneInfo("Asia/Jakarta")).replace(tzinfo=None)
start_date = end_date - pd.DateOffset(years=1)

# Batas pengambilan per aplikasi.
# Naikkan jika status menunjukkan batas tercapai.
MAX_REVIEWS = 20000
PAGE_SIZE = 200

# Tema keluhan berdasarkan kata kunci pada ulasan bintang 1–2.
# Ini identifikasi otomatis awal, perlu dicek dari contoh teks.
complaint_patterns = {
    "Login / account access": (
        r"\blogin\b|\blog in\b|\bmasuk\b|\botp\b|"
        r"\bpassword\b|\bpin\b|\blogout\b"
    ),
    "App stability / speed": (
        r"\blemot\b|\blambat\b|\blag\b|\bhang\b|"
        r"\bcrash\b|\bforce close\b|\berror\b|\bbug\b|"
        r"\bloading\b|\bmacet\b"
    ),
    "Trading / order execution": (
        r"\border\b|\bpesanan\b|\btransaksi\b|"
        r"\bjual\b|\bbeli\b|\btrading\b"
    ),
    "Deposit / withdrawal": (
        r"\bdeposit\b|\bwithdraw\w*\b|\bpenarikan\b|"
        r"\btransfer\b|\bsaldo\b|\brdn\b|\btop up\b"
    ),
    "Customer support": (
        r"\bcs\b|\bcustomer service\b|\bsupport\b|"
        r"\blayanan pelanggan\b|\bkomplain\b"
    ),
    "Charts / market data": (
        r"\bchart\b|\bgrafik\b|\bdata\b|"
        r"\brealtime\b|\breal time\b|\bquote\b"
    ),
}

summary_rows = []
review_frames = []

for competitor, app_id in competitors.items():
    print(f"Collecting: {competitor}")

    collected = []
    seen_ids = set()
    token = None
    status = "Complete to date boundary"

    try:
        while True:
            batch, next_token = reviews(
                app_id,
                lang="id",
                country="id",
                sort=Sort.NEWEST,
                count=PAGE_SIZE,
                continuation_token=token,
            )

            if not batch:
                status = "No more reviews returned"
                break

            batch_dates = []

            for item in batch:
                review_id = item.get("reviewId")
                review_date = item.get("at")

                if review_date is not None:
                    batch_dates.append(pd.Timestamp(review_date))

                if not review_id or review_id in seen_ids:
                    continue

                seen_ids.add(review_id)
                collected.append(item)

            # NEWEST: hentikan setelah seluruh halaman melewati
            # awal periode.
            if batch_dates and max(batch_dates) < start_date:
                break

            if next_token is None:
                status = "No more reviews returned"
                break

            if len(collected) >= MAX_REVIEWS:
                status = "Limit reached — partial sample"
                break

            token = next_token

    except Exception as exc:
        status = f"Extraction error — partial data: {exc}"

    df = pd.DataFrame(collected)

    if not df.empty:
        df["at"] = pd.to_datetime(df["at"], errors="coerce")
        df["score"] = pd.to_numeric(df["score"], errors="coerce")

        df = df.loc[
            df["at"].between(start_date, end_date)
            & df["score"].between(1, 5)
        ].copy()

    n = len(df)

    if n == 0:
        summary_rows.append({
            "App": competitor,
            "Reviews Collected": 0,
            "Avg Review Rating": None,
            "Positive %": None,
            "Neutral %": None,
            "Negative %": None,
            "Top Complaint Theme": "N/A",
            "Theme Mentions": None,
            "Status": status,
        })
        continue

    # Rumus:
    # Persentase kategori = jumlah ulasan kategori / total ulasan * 100
    df["Feedback"] = df["score"].map(
        lambda score: (
            "Positive" if score >= 4
            else "Neutral" if score == 3
            else "Negative"
        )
    )

    positive_pct = df["Feedback"].eq("Positive").mean() * 100
    neutral_pct = df["Feedback"].eq("Neutral").mean() * 100
    negative_pct = df["Feedback"].eq("Negative").mean() * 100

    # Cari tema hanya pada ulasan bintang 1–2.
    negative_text = (
        df.loc[df["Feedback"].eq("Negative"), "content"]
        .fillna("")
        .astype(str)
        .str.lower()
    )

    theme_counts = {
        theme: int(
            negative_text.str.contains(
                pattern, regex=True, flags=re.IGNORECASE
            ).sum()
        )
        for theme, pattern in complaint_patterns.items()
    }

    highest_count = max(theme_counts.values(), default=0)

    if highest_count > 0:
        # Jika jumlah sama, tampilkan semua tema yang seri.
        top_theme = " / ".join(
            theme for theme, count in theme_counts.items()
            if count == highest_count
        )
    else:
        top_theme = "No matching keyword theme"

    summary_rows.append({
        "App": competitor,
        "Reviews Collected": n,
        "Avg Review Rating": df["score"].mean(),
        "Positive %": positive_pct,
        "Neutral %": neutral_pct,
        "Negative %": negative_pct,
        "Top Complaint Theme": top_theme,
        "Theme Mentions": highest_count,
        "Status": status,
    })

    df["Competitor"] = competitor

    # Simpan tema per ulasan agar hasil bisa diperiksa.
    df["Complaint Themes"] = df.apply(
        lambda row: "; ".join(
            theme
            for theme, pattern in complaint_patterns.items()
            if row["score"] <= 2
            and re.search(
                pattern,
                str(row.get("content") or ""),
                flags=re.IGNORECASE,
            )
        ),
        axis=1,
    )

    review_frames.append(df)

# Tabel ringkasan
df_summary = pd.DataFrame(summary_rows)

# Teks ulasan untuk pemeriksaan
df_reviews = (
    pd.concat(review_frames, ignore_index=True)
    if review_frames else pd.DataFrame()
)

print(
    f"\nPERIOD: {start_date:%d %B %Y} "
    f"– {end_date:%d %B %Y, %H:%M} WIB"
)
print("RATING-BASED FEEDBACK — GOOGLE PLAY")

display(
    df_summary.style
    .hide(axis="index")
    .format({
        "Reviews Collected": "{:,.0f}",
        "Avg Review Rating": "{:.2f}",
        "Positive %": "{:.1f}%",
        "Neutral %": "{:.1f}%",
        "Negative %": "{:.1f}%",
        "Theme Mentions": "{:,.0f}",
    }, na_rep="N/A")
)

Collecting: Ajaib
Collecting: Stockbit
Collecting: IPOT
Collecting: Mirae Asset (Neo HOTS)
Collecting: KISI (iKISI)
Collecting: KISI (KOINS Mobile)

PERIOD: 06 October 2025 – 06 October 2026, 08:36 WIB
RATING-BASED FEEDBACK — GOOGLE PLAY

C:\Users\Muhammad Indragiri E\AppData\Local\Temp\ipykernel_42768\358865133.py:222: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(review_frames, ignore_index=True)

In [18]:

#APPLE STORE 
import requests
import pandas as pd
from IPython.display import display

SEARCH_TERMS = {
    "Ajaib": "Ajaib",
    "Stockbit": "Stockbit",
    "IPOT": "IPOT",
    "Mirae Asset (Neo HOTS)": "Neo HOTS",
    "KISI (iKISI)": "iKISI",
    "KISI (KOINS Mobile)": "KOINS",
}

session = requests.Session()
session.headers.update({"User-Agent": "AppReviewResearch/1.0"})

candidates = []

for competitor, term in SEARCH_TERMS.items():
    try:
        response = session.get(
            "https://itunes.apple.com/search",
            params={
                "term": term,
                "country": "id",
                "entity": "software",
                "limit": 10,
            },
            timeout=30,
        )
        response.raise_for_status()

        for item in response.json().get("results", []):
            candidates.append({
                "Competitor": competitor,
                "App Name": item.get("trackName"),
                "Developer": item.get("sellerName"),
                "App ID": item.get("trackId"),
                "App URL": item.get("trackViewUrl"),
            })

    except Exception as exc:
        print(f"FAILED: {competitor} — {exc}")

df_candidates = pd.DataFrame(candidates)

if df_candidates.empty:
    print("Tidak ada hasil pencarian. Cek koneksi atau link App Store.")
else:
    display(df_candidates)

,Competitor,App Name,Developer,App ID,App URL
0,Ajaib,"Ajaib: Stock, Crypto, US Stock",Ajaib Technologies Corporation,1473916571,https://apps.apple.com/id/app/ajaib-stock-crypto-us-stock/id1473916571?uo=4
1,Ajaib,Ajaib Kripto: Buy BTC & Crypto,Ajaib Technologies Corporation,1634168301,https://apps.apple.com/id/app/ajaib-kripto-buy-btc-crypto/id1634168301?uo=4
2,Ajaib,Bibit - Reksadana & Obligasi,"BIBIT TUMBUH BERSAMA, PT",1445856964,https://apps.apple.com/id/app/bibit-reksadana-obligasi/id1445856964?uo=4
3,Ajaib,Stockbit - Stock Investing App,Stockbit Pte Ltd,1184800207,https://apps.apple.com/id/app/stockbit-stock-investing-app/id1184800207?uo=4
4,Ajaib,Pluang: Trading Saham & Crypto,"BUMI SANTOSA CEMERLANG, PT",1341588054,https://apps.apple.com/id/app/pluang-trading-saham-crypto/id1341588054?uo=4
5,Ajaib,Indodax,PT Indodax Nasional Indonesia,1349104693,https://apps.apple.com/id/app/indodax/id1349104693?uo=4
6,Ajaib,Stocks,Apple Distribution International,1069512882,https://apps.apple.com/id/app/stocks/id1069512882?uo=4
7,Ajaib,Binance: Buy Bitcoin & Crypto,Binance Switzerland AG,1436799971,https://apps.apple.com/id/app/binance-buy-bitcoin-crypto/id1436799971?uo=4
8,Ajaib,Pintu Trading Crypto & Futures,PT PINTU KEMANA SAJA,1494119678,https://apps.apple.com/id/app/pintu-trading-crypto-futures/id1494119678?uo=4
9,Ajaib,TradingView: Track All Markets,"TradingView, Inc.",1205990992,https://apps.apple.com/id/app/tradingview-track-all-markets/id1205990992?uo=4
10,Stockbit,Stockbit - Stock Investing App,Stockbit Pte Ltd,1184800207,https://apps.apple.com/id/app/stockbit-stock-investing-app/id1184800207?uo=4
11,Stockbit,"Ajaib: Stock, Crypto, US Stock",Ajaib Technologies Corporation,1473916571,https://apps.apple.com/id/app/ajaib-stock-crypto-us-stock/id1473916571?uo=4
12,Stockbit,Bank Jago/Jago Syariah,PT. Bank Artos Indonesia Tbk,1539402234,https://apps.apple.com/id/app/bank-jago-jago-syariah/id1539402234?uo=4
13,Stockbit,"IPOT: 1 Platform, Your Journey",PT INDO PREMIER SEKURITAS,1514387216,https://apps.apple.com/id/app/ipot-1-platform-your-journey/id1514387216?uo=4
14,Stockbit,Investing.com: Stocks & Shares,Fusion Media Limited,909998122,https://apps.apple.com/id/app/investing-com-stocks-shares/id909998122?uo=4
15,Stockbit,Pintu Trading Crypto & Futures,PT PINTU KEMANA SAJA,1494119678,https://apps.apple.com/id/app/pintu-trading-crypto-futures/id1494119678?uo=4
16,Stockbit,Ajaib Kripto: Buy BTC & Crypto,Ajaib Technologies Corporation,1634168301,https://apps.apple.com/id/app/ajaib-kripto-buy-btc-crypto/id1634168301?uo=4
17,IPOT,"IPOT: 1 Platform, Your Journey",PT INDO PREMIER SEKURITAS,1514387216,https://apps.apple.com/id/app/ipot-1-platform-your-journey/id1514387216?uo=4
18,IPOT,Stockbit - Stock Investing App,Stockbit Pte Ltd,1184800207,https://apps.apple.com/id/app/stockbit-stock-investing-app/id1184800207?uo=4
19,IPOT,Bibit - Reksadana & Obligasi,"BIBIT TUMBUH BERSAMA, PT",1445856964,https://apps.apple.com/id/app/bibit-reksadana-obligasi/id1445856964?uo=4
20,IPOT,"Ajaib: Stock, Crypto, US Stock",Ajaib Technologies Corporation,1473916571,https://apps.apple.com/id/app/ajaib-stock-crypto-us-stock/id1473916571?uo=4
21,IPOT,IPOTGO,PT INDO PREMIER SEKURITAS,1160259651,https://apps.apple.com/id/app/ipotgo/id1160259651?uo=4
22,IPOT,Stocks,Apple Distribution International,1069512882,https://apps.apple.com/id/app/stocks/id1069512882?uo=4
23,IPOT,RTI Business,"RTI Infokom, PT",1114279125,https://apps.apple.com/id/app/rti-business/id1114279125?uo=4
24,IPOT,IPOTKU,PT INDO PREMIER SEKURITAS,1148548939,https://apps.apple.com/id/app/ipotku/id1148548939?uo=4
25,IPOT,IPOTFLEX,PT INDO PREMIER SEKURITAS,1580581666,https://apps.apple.com/id/app/ipotflex/id1580581666?uo=4
26,Mirae Asset (Neo HOTS),Neo HOTS,PT. MIRAE ASSET SEKURITAS INDONESIA,1151264263,https://apps.apple.com/id/app/neo-hots/id1151264263?uo=4
27,Mirae Asset (Neo HOTS),M-STOCK: Aplikasi Investasi,PT. MIRAE ASSET SEKURITAS INDONESIA,1670096144,https://apps.apple.com/id/app/m-stock-aplikasi-investasi/id1670096144?uo=4
28,Mirae Asset (Neo HOTS),Stockbit - Stock Investing App,Stockbit Pte Ltd,1184800207,https://apps.apple.com/id/app/stockbit-stock-investing-app/id1184800207?uo=4
29,Mirae Asset (Neo HOTS),Instagram,"Instagram, Inc.",389801252,https://apps.apple.com/id/app/instagram/id389801252?uo=4
30,Mirae Asset (Neo HOTS),"Ajaib: Stock, Crypto, US Stock",Ajaib Technologies Corporation,1473916571,https://apps.apple.com/id/app/ajaib-stock-crypto-us-stock/id1473916571?uo=4
31,Mirae Asset (Neo HOTS),SeaBank,PT.Bank Seabank Indonesia,1525477806,https://apps.apple.com/id/app/seabank/id1525477806?uo=4
32,Mirae Asset (Neo HOTS),RTI Business,"RTI Infokom, PT",1114279125,https://apps.apple.com/id/app/rti-business/id1114279125?uo=4
33,Mirae Asset (Neo HOTS),Bibit - Reksadana & Obligasi,"BIBIT TUMBUH BERSAMA, PT",1445856964,https://apps.apple.com/id/app/bibit-reksadana-obligasi/id1445856964?uo=4
34,Mirae Asset (Neo HOTS),WhatsApp Messenger,WhatsApp Inc.,310633997,https://apps.apple.com/id/app/whatsapp-messenger/id310633997?uo=4
35,Mirae Asset (Neo HOTS),Jakmall Supplier Dropship,"JAKMALL DIGITAL NIAGA, PT",1426242987,https://apps.apple.com/id/app/jakmall-supplier-dropship/id1426242987?uo=4
36,KISI (iKISI),iKISI - Stock Investing App,"KOREA INVESTMENT AND SEKURITAS INDONESIA, PT",6736644271,https://apps.apple.com/id/app/ikisi-stock-investing-app/id6736644271?uo=4
37,KISI (iKISI),iKIS - KIS Securities,KIS VIETNAM SECURITIES CORPORATION,6474399998,https://apps.apple.com/id/app/ikis-kis-securities/id6474399998?uo=4
38,KISI (KOINS Mobile),KOINS Mobile,"KOREA INVESTMENT AND SEKURITAS INDONESIA, PT",1436459041,https://apps.apple.com/id/app/koins-mobile/id1436459041?uo=4
39,KISI (KOINS Mobile),iKISI - Stock Investing App,"KOREA INVESTMENT AND SEKURITAS INDONESIA, PT",6736644271,https://apps.apple.com/id/app/ikisi-stock-investing-app/id6736644271?uo=4
40,KISI (KOINS Mobile),"Koinz - Order, collect, redeem",GPlanet,1220667985,https://apps.apple.com/id/app/koinz-order-collect-redeem/id1220667985?uo=4
41,KISI (KOINS Mobile),Island King,"HK DENGSHEN TECHNOLOGY CO., LIMITED",1458091391,https://apps.apple.com/id/app/island-king/id1458091391?uo=4
42,KISI (KOINS Mobile),8 Ball Pool™,Miniclip SA,543186831,https://apps.apple.com/id/app/8-ball-pool/id543186831?uo=4
43,KISI (KOINS Mobile),Time Master: Coin & Clash Game,CIAOGAMES LTD,1531154377,https://apps.apple.com/id/app/time-master-coin-clash-game/id1531154377?uo=4
44,KISI (KOINS Mobile),Worms Zone .io — Hungry Snake,AZUR INTERACTIVE GAMES LIMITED,1357967682,https://apps.apple.com/id/app/worms-zone-io-hungry-snake/id1357967682?uo=4

In [19]:
# APP STORE 
import re
import time
import requests
import pandas as pd

from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo
from IPython.display import display

# =========================================================
# 1. APLIKASI — ID DARI HASIL PENCARIAN KAMU
# =========================================================
competitors = {
    "Ajaib": 1473916571,
    "Stockbit": 1184800207,
    "IPOT": 1514387216,
    "Mirae Asset (Neo HOTS)": 1151264263,
    "KISI (iKISI)": 6736644271,
    "KISI (KOINS Mobile)": 1436459041,
}

COUNTRY = "id"
MAX_PAGES = 10

end_date = pd.Timestamp(datetime.now(ZoneInfo("Asia/Jakarta")))
start_date = end_date - pd.DateOffset(years=1)

session = requests.Session()
session.headers.update({"User-Agent": "AppReviewResearch/1.0"})

# =========================================================
# 2. TEMA KELUHAN BERDASARKAN KATA KUNCI
# Hanya dihitung pada review bintang 1–2.
# Satu review dapat menyebut beberapa tema.
# =========================================================
complaint_patterns = {
    "Login / account access": (
        r"\blog[\s-]?in\b|\bmasuk\b|\botp\b|"
        r"\bpassword\b|\bpasword\b|\bsandi\b|\bpin\b|\blogout\b"
    ),
    "Registration / verification": (
        r"\bverifik\w*\b|\bverification\b|\bregistrasi\b|"
        r"\bregistration\b|\bpendaftaran\b|\bdaftar\b|"
        r"\bktp\b|\bbuka akun\b"
    ),
    "App stability / speed": (
        r"\blemot\b|\blelet\b|\blambat\b|\bslow\b|"
        r"\blag\w*\b|\bhang\b|\bcrash\w*\b|"
        r"\bforce close\b|\ber+o+r+\w*\b|"
        r"\bbug\w*\b|\bloading\b|\bmacet\b"
    ),
    "Trading / order execution": (
        r"\border\b|\bpesanan\b|\btransaksi\b|"
        r"\btransaction\w*\b|\bjual\b|\bbeli\b|"
        r"\btrading\b|\bexecution\b"
    ),
    "Deposit / withdrawal": (
        r"\bdeposit\b|\bwithdraw\w*\b|\bwithdrawl\b|"
        r"\bwd\b|\bpenarikan\b|\btransfer\b|\bsaldo\b|"
        r"\bbalance\b|\brdn\b|\btop[\s-]?up\b"
    ),
    "Customer support": (
        r"\bcs\b|\bcustomer service\b|\bcustomer support\b|"
        r"\blayanan pelanggan\b|\bkomplain\b|\brespon\w*\b"
    ),
    "Charts / market data": (
        r"\bchart\w*\b|\bgrafik\b|\bdata\b|"
        r"\brealtime\b|\breal time\b|\bquote\b"
    ),
}

def get_label(entry, key):
    value = entry.get(key, {})
    return value.get("label", "") if isinstance(value, dict) else ""

def detect_themes(text):
    return "; ".join(
        theme
        for theme, pattern in complaint_patterns.items()
        if re.search(pattern, str(text), flags=re.IGNORECASE)
    )

summary_rows = []
review_frames = []

# =========================================================
# 3. AMBIL REVIEW APP STORE INDONESIA
# =========================================================
for competitor, app_id in competitors.items():
    print(f"\nCollecting: {competitor}")

    collected = []
    seen_ids = set()
    status = "Page limit reached — coverage not guaranteed"

    try:
        for page in range(1, MAX_PAGES + 1):
            url = (
                f"https://itunes.apple.com/{COUNTRY}/rss/"
                f"customerreviews/page={page}/id={app_id}/"
                "sortby=mostrecent/json"
            )

            response = session.get(url, timeout=30)
            response.raise_for_status()

            entries = response.json().get("feed", {}).get("entry", [])

            if isinstance(entries, dict):
                entries = [entries]

            # Metadata aplikasi tidak dianggap sebagai review.
            entries = [
                item for item in entries
                if isinstance(item, dict) and "im:rating" in item
            ]

            if not entries:
                status = "Feed ended/empty — coverage not guaranteed"
                break

            new_count = 0
            page_dates = []

            for item in entries:
                review_id = get_label(item, "id")

                review_date = pd.to_datetime(
                    get_label(item, "updated"),
                    utc=True,
                    errors="coerce",
                )

                if pd.notna(review_date):
                    page_dates.append(review_date)

                if not review_id or review_id in seen_ids:
                    continue

                seen_ids.add(review_id)
                new_count += 1

                title = get_label(item, "title")
                content = get_label(item, "content")

                collected.append({
                    "Competitor": competitor,
                    "Platform": "App Store",
                    "Storefront": "Indonesia",
                    "App_ID": app_id,
                    "reviewId": review_id,
                    "at": review_date,
                    "score": pd.to_numeric(
                        get_label(item, "im:rating"),
                        errors="coerce",
                    ),
                    "title": title,
                    "content": content,
                    "Review_Text": f"{title} {content}".strip(),
                })

            print(f"  Page {page}: {new_count} new reviews")

            if new_count == 0:
                status = "Repeated page — coverage not guaranteed"
                break

            if (
                len(page_dates) == len(entries)
                and max(page_dates) < start_date.tz_convert("UTC")
            ):
                status = "Date boundary reached — feed coverage unverified"
                break

            time.sleep(0.5)

    except Exception as exc:
        status = f"Extraction error — partial data: {exc}"

    df = pd.DataFrame(collected)

    if not df.empty:
        df["at"] = pd.to_datetime(df["at"], utc=True, errors="coerce")
        df["at"] = df["at"].dt.tz_convert("Asia/Jakarta")

        df = df.loc[
            df["at"].between(start_date, end_date)
            & df["score"].between(1, 5)
        ].copy()

    n = len(df)

    if n == 0:
        summary_rows.append({
            "App": competitor,
            "Reviews Collected": 0,
            "Status": status,
        })
        print("  Tidak ada review valid dalam periode.")
        continue

    # =====================================================
    # 4. KATEGORI BERDASARKAN BINTANG
    # Positive: 4–5, Neutral: 3, Negative: 1–2
    # =====================================================
    df["Feedback"] = df["score"].map(
        lambda score: (
            "Positive" if score >= 4
            else "Neutral" if score == 3
            else "Negative"
        )
    )

    df["Complaint Themes"] = df.apply(
        lambda row: detect_themes(row["Review_Text"])
        if row["Feedback"] == "Negative" else "",
        axis=1,
    )

    negative_text = df.loc[
        df["Feedback"].eq("Negative"), "Review_Text"
    ]

    theme_counts = {
        theme: int(
            negative_text.str.contains(
                pattern,
                regex=True,
                flags=re.IGNORECASE,
                na=False,
            ).sum()
        )
        for theme, pattern in complaint_patterns.items()
    }

    highest_count = max(theme_counts.values(), default=0)

    top_theme = (
        "; ".join(
            theme
            for theme, count in theme_counts.items()
            if count == highest_count
        )
        if highest_count > 0
        else "No matching keyword theme"
    )

    summary_rows.append({
        "App": competitor,
        "Reviews Collected": n,
        "Avg Review Rating": df["score"].mean(),
        "Positive %": df["Feedback"].eq("Positive").mean() * 100,
        "Neutral %": df["Feedback"].eq("Neutral").mean() * 100,
        "Negative %": df["Feedback"].eq("Negative").mean() * 100,
        "Top Complaint Theme": top_theme,
        "Theme Mentions": highest_count,
        "Status": status,
        "Oldest Retrieved": df["at"].min().strftime("%Y-%m-%d"),
        "Newest Retrieved": df["at"].max().strftime("%Y-%m-%d"),
    })

    review_frames.append(df)

# =========================================================
# 5. HASIL TABEL
# =========================================================
ppt_columns = [
    "App",
    "Reviews Collected",
    "Avg Review Rating",
    "Positive %",
    "Neutral %",
    "Negative %",
    "Top Complaint Theme",
    "Theme Mentions",
    "Status",
]

df_appstore_summary = pd.DataFrame(summary_rows).reindex(
    columns=ppt_columns + ["Oldest Retrieved", "Newest Retrieved"]
)

df_appstore_reviews = (
    pd.concat(review_frames, ignore_index=True)
    if review_frames else pd.DataFrame()
)

print(
    f"\nPERIOD: {start_date:%d %B %Y} "
    f"– {end_date:%d %B %Y, %H:%M} WIB"
)
print("APP STORE INDONESIA — RATING-BASED FEEDBACK")

display(
    df_appstore_summary[ppt_columns].style
    .hide(axis="index")
    .format({
        "Reviews Collected": "{:,.0f}",
        "Avg Review Rating": "{:.2f}",
        "Positive %": "{:.1f}%",
        "Neutral %": "{:.1f}%",
        "Negative %": "{:.1f}%",
        "Theme Mentions": "{:,.0f}",
    }, na_rep="N/A")
)

# =========================================================
# 6. SIMPAN EXCEL DAN CSV
# Menggunakan folder kerja notebook saat ini.
# =========================================================
output_dir = Path.cwd()
timestamp = end_date.strftime("%Y%m%d_%H%M%S")

export_reviews = df_appstore_reviews.copy()

if not export_reviews.empty:
    export_reviews["at"] = export_reviews["at"].map(
        lambda value: value.isoformat() if pd.notna(value) else ""
    )

excel_file = output_dir / f"AppStore_Indonesia_{timestamp}.xlsx"
csv_file = output_dir / f"AppStore_Indonesia_Reviews_{timestamp}.csv"

with pd.ExcelWriter(excel_file, engine="openpyxl") as writer:
    df_appstore_summary.to_excel(
        writer, sheet_name="Summary", index=False
    )
    export_reviews.to_excel(
        writer, sheet_name="Review_Detail", index=False
    )
    pd.DataFrame([{
        "Period Start": start_date.isoformat(),
        "Period End": end_date.isoformat(),
        "Storefront": "Indonesia",
        "Classification": "4–5 Positive; 3 Neutral; 1–2 Negative",
        "Themes": "Keyword matches within 1–2-star reviews",
        "Coverage": "Retrieved sample; full-year completeness unverified",
    }]).to_excel(writer, sheet_name="Methodology", index=False)

export_reviews.to_csv(csv_file, index=False, encoding="utf-8-sig")

print(f"\nExcel: {excel_file.resolve()}")
print(f"CSV  : {csv_file.resolve()}")

Collecting: Ajaib
  Page 1: 50 new reviews
  Page 2: 50 new reviews
  Page 3: 50 new reviews
  Page 4: 50 new reviews
  Page 5: 50 new reviews
  Page 6: 50 new reviews
  Page 7: 50 new reviews
  Page 8: 50 new reviews
  Page 9: 50 new reviews
  Page 10: 50 new reviews

Collecting: Stockbit
  Page 1: 50 new reviews
  Page 2: 50 new reviews
  Page 3: 50 new reviews
  Page 4: 50 new reviews
  Page 5: 50 new reviews
  Page 6: 50 new reviews
  Page 7: 50 new reviews
  Page 8: 50 new reviews
  Page 9: 50 new reviews
  Page 10: 50 new reviews

Collecting: IPOT
  Page 1: 50 new reviews
  Page 2: 50 new reviews
  Page 3: 50 new reviews
  Page 4: 50 new reviews
  Page 5: 50 new reviews
  Page 6: 50 new reviews
  Page 7: 50 new reviews
  Page 8: 50 new reviews
  Page 9: 50 new reviews
  Page 10: 50 new reviews

Collecting: Mirae Asset (Neo HOTS)
  Page 1: 50 new reviews
  Page 2: 50 new reviews

Collecting: KISI (iKISI)
  Page 1: 45 new reviews

Collecting: KISI (KOINS Mobile)
  Page 1: 30 new reviews

PERIOD: 08 October 2025 – 08 October 2026, 08:55 WIB
APP STORE INDONESIA — RATING-BASED FEEDBACK

Excel: D:\KISI_Competitor_Analysis\AppStore_Indonesia_20261008_085539.xlsx
CSV  : D:\KISI_Competitor_Analysis\AppStore_Indonesia_Reviews_20261008_085539.csv

In [22]:
import re
import time
import requests
import pandas as pd

from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo
from google_play_scraper import reviews, Sort
from IPython.display import display

# =========================================================
# 1. KONFIGURASI
# =========================================================
APPS = {
    "Ajaib": {
        "google_play": "ajaib.co.id",
        "app_store": 1473916571,
    },
    "Stockbit": {
        "google_play": "com.stockbit.android",
        "app_store": 1184800207,
    },
    "IPOT": {
        "google_play": "com.indopremier.ipot",
        "app_store": 1514387216,
    },
    "Mirae Asset (Neo HOTS)": {
        "google_play": "id.co.miraeassetdaewoo",
        "app_store": 1151264263,
    },
    "KISI (iKISI)": {
        "google_play": "com.koreainvestment.indonesia",
        "app_store": 6736644271,
    },
    "KISI (KOINS Mobile)": {
        "google_play": "com.koins.mtsand",
        "app_store": 1436459041,
    },
}

# Seluruh tanggal 6 Oktober 2026 termasuk dalam periode.
START = pd.Timestamp("2025-10-06 00:00:00", tz="Asia/Jakarta")
END = pd.Timestamp("2026-10-07 00:00:00", tz="Asia/Jakarta")

GOOGLE_MAX_REVIEWS = 20000
GOOGLE_PAGE_SIZE = 200
APPLE_MAX_PAGES = 10

# Asumsi untuk timestamp Google Play tanpa timezone.
# Mengikuti perlakuan pada kode sebelumnya.
GOOGLE_NAIVE_TZ = "Asia/Jakarta"

# Dua contoh per kategori untuk setiap aplikasi/platform.
EXAMPLES_PER_CATEGORY = 2

OUTPUT_DIR = Path(r"D:\KISI_Competitor_Analysis")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

RUN_ID = datetime.now(
    ZoneInfo("Asia/Jakarta")
).strftime("%Y%m%d_%H%M%S")

session = requests.Session()
session.headers.update({"User-Agent": "AppReviewResearch/1.0"})

# =========================================================
# 2. ATURAN TEMA IDENTIK
# Tema diperoleh melalui kata kunci, bukan RoBERTa.
# =========================================================
THEMES = {
    "Login / account access": (
        r"\blog[\s-]?in\b|\bsign[\s-]?in\b|\botp\b|"
        r"\bpassword\b|\bpasword\b|\bsandi\b|\bpin\b|"
        r"\blogout\b|\bmasuk akun\b"
    ),
    "Registration / verification": (
        r"\bverifik\w*\b|\bverif\b|\bverification\b|"
        r"\bregistrasi\b|\bregistration\b|\bpendaftaran\b|"
        r"\bdaftar\b|\bsign[\s-]?up\b|\bktp\b|\bbuka akun\b"
    ),
    "App stability / speed": (
        r"\blemot\b|\blelet\b|\blambat\b|\bslow\b|"
        r"\blag\w*\b|\bnge(?:lag|leg)\w*\b|\bhang\b|"
        r"\bcrash\w*\b|\bforce close\b|\ber+o+r+\w*\b|"
        r"\bbug\w*\b|\bloading\b|\bmacet\b|\bfreeze\w*\b"
    ),
    "Trading / order execution": (
        r"\border\b|\bpesanan\b|\btransaksi\b|"
        r"\btransaction\w*\b|\bjual\b|\bbeli\b|"
        r"\btrading\b|\beksekusi\b|\bexecution\b|"
        r"\bmatched\b|\breject\w*\b"
    ),
    "Deposit / withdrawal": (
        r"\bdeposit\b|\bwithdraw\w*\b|\bwitdhraw\w*\b|"
        r"\bwd\b|\bpenarikan\b|\btransfer\b|\bsaldo\b|"
        r"\bbalance\b|\brdn\b|\btop[\s-]?up\b|"
        r"\btarik (?:saldo|dana|uang)\b"
    ),
    "Customer support": (
        r"\bcs\b|\bcustomer service\b|\bcustomer support\b|"
        r"\blayanan pelanggan\b|\bkomplain\b|"
        r"\brespon\w*\b|\bresponse\b|\blive chat\b"
    ),
    "Charts / market data": (
        r"\bchart\w*\b|\bgrafik\b|\bcandle\w*\b|"
        r"\bdata\b|\brealtime\b|\breal time\b|"
        r"\bquote\b|\border[\s-]?book\b"
    ),
    "Fees / charges": (
        r"\bfee\w*\b|\bbiaya\b|\bkomisi\b|"
        r"\bcommission\w*\b|\bpotongan\b|\btarif\b"
    ),
}

COMPILED = {
    theme: re.compile(pattern, re.IGNORECASE)
    for theme, pattern in THEMES.items()
}

RAW_COLUMNS = [
    "Platform", "Competitor", "App_ID",
    "reviewId", "at", "score", "content",
]

# =========================================================
# 3. FUNGSI BANTU
# =========================================================
def to_wib(value, naive_timezone):
    try:
        ts = pd.Timestamp(value)
        if pd.isna(ts):
            return pd.NaT
        if ts.tzinfo is None:
            ts = ts.tz_localize(naive_timezone)
        return ts.tz_convert("Asia/Jakarta")
    except (ValueError, TypeError):
        return pd.NaT


def get_label(entry, key):
    value = entry.get(key, {})
    return value.get("label", "") if isinstance(value, dict) else ""


def save_checkpoint(rows):
    frame = pd.DataFrame(rows, columns=RAW_COLUMNS)
    frame["at"] = frame["at"].map(
        lambda value: value.isoformat() if pd.notna(value) else ""
    )
    frame.to_csv(
        OUTPUT_DIR / f"App_Reviews_Raw_{RUN_ID}.csv",
        index=False,
        encoding="utf-8-sig",
    )


# =========================================================
# 4. PENGAMBILAN GOOGLE PLAY
# =========================================================
def collect_google(app_name, app_id):
    rows, seen = [], set()
    token = None
    page = 0
    status = "Limit reached — partial sample"

    try:
        while len(rows) < GOOGLE_MAX_REVIEWS:
            page += 1
            batch, next_token = reviews(
                app_id,
                lang="id",
                country="id",
                sort=Sort.NEWEST,
                count=min(
                    GOOGLE_PAGE_SIZE,
                    GOOGLE_MAX_REVIEWS - len(rows),
                ),
                continuation_token=token,
            )

            if not batch:
                status = "No more reviews returned — coverage unverified"
                break

            dates = []
            new_count = 0

            for item in batch:
                date = to_wib(item.get("at"), GOOGLE_NAIVE_TZ)
                if pd.notna(date):
                    dates.append(date)

                review_id = str(item.get("reviewId") or "")
                if not review_id or review_id in seen:
                    continue

                seen.add(review_id)
                new_count += 1
                rows.append({
                    "Platform": "Google Play",
                    "Competitor": app_name,
                    "App_ID": app_id,
                    "reviewId": review_id,
                    "at": date,
                    "score": item.get("score"),
                    "content": item.get("content") or "",
                })

            if page == 1 or page % 10 == 0:
                print(f"  Page {page}: {len(rows):,} retrieved")

            if new_count == 0:
                status = "Repeated page — coverage unverified"
                break
            if len(dates) == len(batch) and max(dates) < START:
                status = "Date boundary reached — newest-order assumption"
                break
            if next_token is None:
                status = "No more reviews returned — coverage unverified"
                break

            token = next_token
            time.sleep(0.2)

    except Exception as exc:
        status = f"Extraction error — partial data: {exc}"

    return rows, status


# =========================================================
# 5. PENGAMBILAN APP STORE INDONESIA
# =========================================================
def collect_apple(app_name, app_id):
    rows, seen = [], set()
    status = "Page limit reached — coverage not guaranteed"

    try:
        for page in range(1, APPLE_MAX_PAGES + 1):
            url = (
                "https://itunes.apple.com/id/rss/"
                f"customerreviews/page={page}/id={app_id}/"
                "sortby=mostrecent/json"
            )

            response = session.get(url, timeout=30)
            response.raise_for_status()

            entries = response.json().get("feed", {}).get("entry", [])
            if isinstance(entries, dict):
                entries = [entries]

            entries = [
                item for item in entries
                if isinstance(item, dict) and "im:rating" in item
            ]

            if not entries:
                status = "Feed ended/empty — coverage not guaranteed"
                break

            dates = []
            new_count = 0

            for item in entries:
                date = to_wib(get_label(item, "updated"), "UTC")
                if pd.notna(date):
                    dates.append(date)

                review_id = str(get_label(item, "id"))
                if not review_id or review_id in seen:
                    continue

                seen.add(review_id)
                new_count += 1
                rows.append({
                    "Platform": "App Store",
                    "Competitor": app_name,
                    "App_ID": app_id,
                    "reviewId": review_id,
                    "at": date,
                    "score": get_label(item, "im:rating"),
                    # Body saja agar sama dengan Google Play.
                    "content": get_label(item, "content"),
                })

            print(f"  Page {page}: {new_count} new reviews")

            if new_count == 0:
                status = "Repeated page — coverage not guaranteed"
                break
            if len(dates) == len(entries) and max(dates) < START:
                status = "Date boundary reached — feed coverage unverified"
                break

            time.sleep(0.5)

    except Exception as exc:
        status = f"Extraction error — partial data: {exc}"

    return rows, status


# =========================================================
# 6. TARIK KEDUA PLATFORM
# =========================================================
all_rows = []
collection_log = []

print("PERIOD: 06 October 2025 – 06 October 2026, WIB")

for app_name, ids in APPS.items():
    for platform, collector, app_id in [
        ("Google Play", collect_google, ids["google_play"]),
        ("App Store", collect_apple, ids["app_store"]),
    ]:
        print(f"\nCollecting: {platform} — {app_name}")
        rows, status = collector(app_name, app_id)
        all_rows.extend(rows)

        collection_log.append({
            "Platform": platform,
            "App": app_name,
            "Retrieved Before Filtering": len(rows),
            "Status": status,
        })

        save_checkpoint(all_rows)
        print(f"  Retrieved: {len(rows):,} | {status}")

df_raw = pd.DataFrame(all_rows, columns=RAW_COLUMNS)
df_collection_log = pd.DataFrame(collection_log)

# =========================================================
# 7. FILTER PERIODE DAN KATEGORI RATING
# =========================================================
df_detail = df_raw.copy()

df_detail["at"] = pd.to_datetime(
    df_detail["at"], utc=True, errors="coerce"
).dt.tz_convert("Asia/Jakarta")

df_detail["score"] = pd.to_numeric(
    df_detail["score"], errors="coerce"
)

df_detail = df_detail.loc[
    df_detail["at"].ge(START)
    & df_detail["at"].lt(END)
    & df_detail["score"].isin([1, 2, 3, 4, 5])
].copy()

df_detail = df_detail.drop_duplicates(
    ["Platform", "Competitor", "reviewId"]
).reset_index(drop=True)

# Pertahankan teks asli untuk kutipan.
df_detail["content"] = df_detail["content"].fillna("").astype(str)
df_detail["Analysis_Text"] = df_detail["content"].str.strip()

df_detail["Feedback"] = df_detail["score"].map({
    1: "Negative", 2: "Negative",
    3: "Neutral",
    4: "Positive", 5: "Positive",
})

df_detail["Matched_Themes"] = [
    [
        theme for theme, pattern in COMPILED.items()
        if pattern.search(text)
    ] if feedback in ["Positive", "Negative"] else []
    for text, feedback in zip(
        df_detail["Analysis_Text"], df_detail["Feedback"]
    )
]

df_detail["Review Themes"] = df_detail["Matched_Themes"].map(
    lambda matches: "; ".join(matches)
)

# =========================================================
# 8. TEMA TERATAS DAN CONTOH REVIEW ASLI
# Pilihan contoh:
# - Kategori rating sesuai.
# - Memuat salah satu tema teratas.
# - Dua teks berbeda terbaru.
# - Jika tidak ada tema cocok, gunakan contoh kategori tersebut
#   dan tandai sebagai general category example.
# =========================================================
def summarize_category(group, feedback):
    selected = group.loc[group["Feedback"].eq(feedback)].copy()

    counts = {
        theme: sum(theme in matches for matches in selected["Matched_Themes"])
        for theme in THEMES
    }

    highest = max(counts.values(), default=0)
    top_themes = [
        theme for theme, count in counts.items()
        if count == highest and highest > 0
    ]

    if selected.empty:
        top_label = "No reviews in this category"
        mentions = None
    elif not top_themes:
        top_label = "No matching keyword theme"
        mentions = 0
    else:
        top_label = "; ".join(top_themes)
        mentions = highest

    candidates = selected.loc[selected["Analysis_Text"].ne("")].copy()

    if top_themes:
        candidates = candidates.loc[
            candidates["Matched_Themes"].map(
                lambda matches: any(theme in matches for theme in top_themes)
            )
        ]
        selection_type = "Matches a top theme"
    else:
        selection_type = "General category example — no matched theme"

    examples = (
        candidates.sort_values(
            ["at", "reviewId"],
            ascending=[False, True],
        )
        .drop_duplicates("Analysis_Text")
        .head(EXAMPLES_PER_CATEGORY)
    )

    return top_label, mentions, counts, len(selected), examples, selection_type


# =========================================================
# 9. RINGKASAN + CONTOH + JUMLAH SETIAP TEMA
# =========================================================
summary_rows = []
theme_rows = []
example_rows = []

for log in collection_log:
    platform, app_name = log["Platform"], log["App"]

    group = df_detail.loc[
        df_detail["Platform"].eq(platform)
        & df_detail["Competitor"].eq(app_name)
    ]

    n = len(group)
    result = {
        "Platform": platform,
        "App": app_name,
        "Reviews Collected": n,
        "Avg Review Rating": group["score"].mean() if n else None,
        "Positive %": (
            group["Feedback"].eq("Positive").mean() * 100 if n else None
        ),
        "Neutral %": (
            group["Feedback"].eq("Neutral").mean() * 100 if n else None
        ),
        "Negative %": (
            group["Feedback"].eq("Negative").mean() * 100 if n else None
        ),
        "Oldest Retrieved": (
            group["at"].min().strftime("%Y-%m-%d") if n else None
        ),
        "Newest Retrieved": (
            group["at"].max().strftime("%Y-%m-%d") if n else None
        ),
        "Status": log["Status"],
    }

    for feedback in ["Positive", "Negative"]:
        top_label, mentions, counts, category_n, examples, selection = (
            summarize_category(group, feedback)
        )

        result[f"Top Theme in {feedback} Reviews"] = top_label
        result[f"{feedback} Theme Mentions"] = mentions

        # Contoh dimasukkan langsung pada tabel ringkasan.
        for number in range(1, EXAMPLES_PER_CATEGORY + 1):
            result[f"{feedback} Example {number}"] = None
            result[f"{feedback} Example {number} Stars"] = None

        for number, (_, row) in enumerate(examples.iterrows(), start=1):
            result[f"{feedback} Example {number}"] = row["content"]
            result[f"{feedback} Example {number} Stars"] = int(row["score"])

            example_rows.append({
                "Platform": platform,
                "App": app_name,
                "Rating Category": feedback,
                "Top Theme": top_label,
                "Matched Themes": row["Review Themes"],
                "Example Selection": selection,
                "Review": row["content"],
                "Stars": int(row["score"]),
                "Date WIB": row["at"].isoformat(),
                "reviewId": row["reviewId"],
            })

        for theme, count in counts.items():
            theme_rows.append({
                "Platform": platform,
                "App": app_name,
                "Rating Category": feedback,
                "Theme": theme,
                "Theme Mentions": count,
                "Reviews in Category": category_n,
            })

    summary_rows.append(result)

df_summary = pd.DataFrame(summary_rows)
df_theme_counts = pd.DataFrame(theme_rows)

example_columns = [
    "Platform", "App", "Rating Category", "Top Theme",
    "Matched Themes", "Example Selection",
    "Review", "Stars", "Date WIB", "reviewId",
]
df_examples = pd.DataFrame(example_rows, columns=example_columns)

# =========================================================
# 10. TAMPILKAN TABEL RINGKASAN
# Contoh pertama ada langsung di samping tema masing-masing.
# Dua contoh lengkap tersedia pada tabel berikut dan Excel.
# =========================================================
summary_columns = [
    "Platform", "App", "Reviews Collected", "Avg Review Rating",
    "Positive %", "Neutral %", "Negative %",
    "Top Theme in Positive Reviews", "Positive Theme Mentions",
    "Positive Example 1", "Positive Example 1 Stars",
    "Top Theme in Negative Reviews", "Negative Theme Mentions",
    "Negative Example 1", "Negative Example 1 Stars",
    "Status",
]

print("\nSUMMARY — SAME RATING AND THEME RULES")

display(
    df_summary[summary_columns].style
    .hide(axis="index")
    .format({
        "Reviews Collected": "{:,.0f}",
        "Avg Review Rating": "{:.2f}",
        "Positive %": "{:.1f}%",
        "Neutral %": "{:.1f}%",
        "Negative %": "{:.1f}%",
        "Positive Theme Mentions": "{:,.0f}",
        "Negative Theme Mentions": "{:,.0f}",
        "Positive Example 1 Stars": "{:.0f}",
        "Negative Example 1 Stars": "{:.0f}",
    }, na_rep="N/A")
)

print("\nREVIEW EXAMPLES — UP TO TWO PER CATEGORY")

display(
    df_examples.style
    .hide(axis="index")
    .format({"Stars": "{:.0f}"}, na_rep="N/A")
)

# Detail untuk analisis berikutnya.
df_reviews = df_detail.loc[
    df_detail["Platform"].eq("Google Play")
].copy()

df_appstore_reviews = df_detail.loc[
    df_detail["Platform"].eq("App Store")
].copy()

# =========================================================
# 11. SIMPAN EXCEL DAN CSV
# =========================================================
export_detail = df_detail.drop(columns="Matched_Themes").copy()
export_detail["at"] = export_detail["at"].map(
    lambda value: value.isoformat()
)

methodology = pd.DataFrame([
    {
        "Item": "Period",
        "Rule": "06 October 2025–06 October 2026 inclusive, WIB",
    },
    {
        "Item": "Store selection",
        "Rule": "Indonesia settings; reviewer nationality/language not guaranteed",
    },
    {
        "Item": "Rating categories",
        "Rule": "4–5 Positive; 3 Neutral; 1–2 Negative. Not text sentiment.",
    },
    {
        "Item": "Themes",
        "Rule": "Same keyword matching on review bodies for both platforms",
    },
    {
        "Item": "Theme Mentions",
        "Rule": "Once per review per theme; multiple themes allowed",
    },
    {
        "Item": "Examples",
        "Rule": (
            "Up to two distinct latest texts per category matching a top theme; "
            "general category examples used if no theme matches. "
            "Illustrative, not representative of the entire sample."
        ),
    },
    {
        "Item": "Interpretation",
        "Rule": (
            "Positive-rated reviews can contain complaints; negative-rated "
            "reviews can contain praise. Theme mentions do not prove aspect sentiment."
        ),
    },
    {
        "Item": "Validation",
        "Rule": "Keyword matches and examples require manual review; not RoBERTa",
    },
    {
        "Item": "Google Play timestamps",
        "Rule": f"Naive timestamps assumed {GOOGLE_NAIVE_TZ}",
    },
    {
        "Item": "Coverage",
        "Rule": (
            f"Google Play limit: {GOOGLE_MAX_REVIEWS} retrieved/app; "
            f"App Store limit: {APPLE_MAX_PAGES} pages/app. "
            "Full-year coverage not guaranteed."
        ),
    },
    {
        "Item": "Historical limitation",
        "Rule": "Retrospective retrieval; deleted or updated reviews may differ",
    },
])

# Hindari teks review dianggap formula oleh Excel.
# CSV tetap mempertahankan teks asli.
def excel_safe(frame):
    frame = frame.copy()
    for column in frame.select_dtypes(include=["object", "string"]).columns:
        frame[column] = frame[column].map(
            lambda value: "'" + value
            if isinstance(value, str)
            and value.startswith(("=", "+", "-", "@"))
            else value
        )
    return frame

excel_file = OUTPUT_DIR / f"App_Review_Comparison_{RUN_ID}.xlsx"
detail_csv = OUTPUT_DIR / f"App_Review_Detail_{RUN_ID}.csv"
examples_csv = OUTPUT_DIR / f"App_Review_Examples_{RUN_ID}.csv"

export_detail.to_csv(detail_csv, index=False, encoding="utf-8-sig")
df_examples.to_csv(examples_csv, index=False, encoding="utf-8-sig")

with pd.ExcelWriter(excel_file, engine="openpyxl") as writer:
    for sheet_name, frame in [
        ("Combined_Summary", df_summary),
        ("Review_Examples", df_examples),
        ("Review_Detail", export_detail),
        ("Theme_Counts", df_theme_counts),
        ("Collection_Log", df_collection_log),
        ("Methodology", methodology),
    ]:
        excel_safe(frame).to_excel(
            writer, sheet_name=sheet_name, index=False
        )

print(f"\nExcel:\n{excel_file}")
print(f"\nCSV detail:\n{detail_csv}")
print(f"\nCSV contoh:\n{examples_csv}")

PERIOD: 06 October 2025 – 06 October 2026, WIB

Collecting: Google Play — Ajaib
  Page 1: 200 retrieved
  Page 10: 2,000 retrieved
  Page 20: 4,000 retrieved
  Page 30: 6,000 retrieved
  Page 40: 8,000 retrieved
  Page 50: 10,000 retrieved
  Page 60: 12,000 retrieved
  Page 70: 14,000 retrieved
  Retrieved: 15,800 | Date boundary reached — newest-order assumption

Collecting: App Store — Ajaib
  Page 1: 50 new reviews
  Page 2: 50 new reviews
  Page 3: 50 new reviews
  Page 4: 50 new reviews
  Page 5: 50 new reviews
  Page 6: 50 new reviews
  Page 7: 50 new reviews
  Page 8: 50 new reviews
  Page 9: 50 new reviews
  Page 10: 50 new reviews
  Retrieved: 500 | Page limit reached — coverage not guaranteed

Collecting: Google Play — Stockbit
  Page 1: 200 retrieved
  Page 10: 2,000 retrieved
  Page 20: 4,000 retrieved
  Page 30: 6,000 retrieved
  Retrieved: 6,200 | Date boundary reached — newest-order assumption

Collecting: App Store — Stockbit
  Page 1: 50 new reviews
  Page 2: 50 new reviews
  Page 3: 50 new reviews
  Page 4: 50 new reviews
  Page 5: 50 new reviews
  Page 6: 50 new reviews
  Page 7: 50 new reviews
  Page 8: 50 new reviews
  Page 9: 50 new reviews
  Page 10: 50 new reviews
  Retrieved: 500 | Page limit reached — coverage not guaranteed

Collecting: Google Play — IPOT
  Page 1: 200 retrieved
  Page 10: 2,000 retrieved
  Retrieved: 2,000 | Date boundary reached — newest-order assumption

Collecting: App Store — IPOT
  Page 1: 50 new reviews
  Page 2: 50 new reviews
  Page 3: 50 new reviews
  Page 4: 50 new reviews
  Page 5: 50 new reviews
  Page 6: 50 new reviews
  Page 7: 50 new reviews
  Page 8: 50 new reviews
  Page 9: 50 new reviews
  Page 10: 50 new reviews
  Retrieved: 500 | Page limit reached — coverage not guaranteed

Collecting: Google Play — Mirae Asset (Neo HOTS)
  Page 1: 200 retrieved
  Retrieved: 400 | Date boundary reached — newest-order assumption

Collecting: App Store — Mirae Asset (Neo HOTS)
  Page 1: 50 new reviews
  Page 2: 50 new reviews
  Retrieved: 100 | Date boundary reached — feed coverage unverified

Collecting: Google Play — KISI (iKISI)
  Page 1: 165 retrieved
  Retrieved: 165 | No more reviews returned — coverage unverified

Collecting: App Store — KISI (iKISI)
  Page 1: 45 new reviews
  Retrieved: 45 | Feed ended/empty — coverage not guaranteed

Collecting: Google Play — KISI (KOINS Mobile)
  Page 1: 200 retrieved
  Retrieved: 286 | Date boundary reached — newest-order assumption

Collecting: App Store — KISI (KOINS Mobile)
  Page 1: 30 new reviews
  Retrieved: 30 | Feed ended/empty — coverage not guaranteed

SUMMARY — SAME RATING AND THEME RULES

REVIEW EXAMPLES — UP TO TWO PER CATEGORY

Excel:
D:\KISI_Competitor_Analysis\App_Review_Comparison_20261008_092207.xlsx

CSV detail:
D:\KISI_Competitor_Analysis\App_Review_Detail_20261008_092207.csv

CSV contoh:
D:\KISI_Competitor_Analysis\App_Review_Examples_20261008_092207.csv

In [37]:
%pip install torch transformers sentencepiece tqdm

Collecting torch
  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/fe/54/4e0a71376b2fb15aaf65ed9e6a4c8043d36f554338c6daabc63059a5e157/torch-2.14.1-cp311-cp311-win_amd64.whl.metadata
  Downloading torch-2.14.1-cp311-cp311-win_amd64.whl.metadata (38 kB)
Requirement already satisfied: transformers in d:\anacondaupdate\lib\site-packages (2.1.1)
Collecting sentencepiece
  Obtaining dependency information for sentencepiece from https://files.pythonhosted.org/packages/ab/62/9e2569867e3dcff7ad6d89642a9615b9801b5cd698abe7df3b490361f66e/sentencepiece-0.2.2-cp311-cp311-win_amd64.whl.metadata
  Downloading sentencepiece-0.2.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Requirement already satisfied: tqdm in d:\anacondaupdate\lib\site-packages (4.65.0)
Requirement already satisfied: filelock in d:\anacondaupdate\lib\site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions>=4.10.0 in d:\anacondaupdate\lib\site-packages (from torch) (4.16.0)
Collecting setuptools>=77.0.3 (from torch)
  Obtaining dependency information for setuptools>=77.0.3 from https://files.pythonhosted.org/packages/95/9c/c510029fc6ef33a6275cd2c5d3cecd6613dfd6aa401d57c54f1c18852ccf/setuptools-84.0.0-py3-none-any.whl.metadata
  Downloading setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)
  Obtaining dependency information for sympy>=1.13.3 from https://files.pythonhosted.org/packages/a2/09/77d55d46fd61b4a135c444fc97158ef34a095e5681d0a6c10b75bf356191/sympy-1.14.0-py3-none-any.whl.metadata
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in d:\anacondaupdate\lib\site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in d:\anacondaupdate\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec>=0.8.5 in d:\anacondaupdate\lib\site-packages (from torch) (2023.3.0)
Requirement already satisfied: numpy in d:\anacondaupdate\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: boto3 in d:\anacondaupdate\lib\site-packages (from transformers) (1.24.28)
Requirement already satisfied: requests in d:\anacondaupdate\lib\site-packages (from transformers) (2.31.0)
Requirement already satisfied: regex in d:\anacondaupdate\lib\site-packages (from transformers) (2022.7.9)
Requirement already satisfied: sacremoses in d:\anacondaupdate\lib\site-packages (from transformers) (0.0.43)
Requirement already satisfied: colorama in d:\anacondaupdate\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\anacondaupdate\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: botocore<1.28.0,>=1.27.28 in d:\anacondaupdate\lib\site-packages (from boto3->transformers) (1.27.59)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in d:\anacondaupdate\lib\site-packages (from boto3->transformers) (0.10.0)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in d:\anacondaupdate\lib\site-packages (from boto3->transformers) (0.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anacondaupdate\lib\site-packages (from jinja2->torch) (2.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anacondaupdate\lib\site-packages (from requests->transformers) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anacondaupdate\lib\site-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anacondaupdate\lib\site-packages (from requests->transformers) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in d:\anacondaupdate\lib\site-packages (from requests->transformers) (2026.7.22)
Requirement already satisfied: six in d:\anacondaupdate\lib\site-packages (from sacremoses->transformers) (1.17.0)
Requirement already satisfied: click in d:\anacondaupdate\lib\site-packages (from sacremoses->transformers) (8.0.4)
Requirement already satisfied: joblib in d:\anacondaupdate\lib\site-packages (from sacremoses->transformers) (1.2.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in d:\anacondaupdate\lib\site-packages (from botocore<1.28.0,>=1.27.28->boto3->transformers) (2.9.0.post0)
Downloading torch-2.14.1-cp311-cp311-win_amd64.whl (124.1 MB)
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.1 MB 2.0 MB/s eta 0:01:01
   ---------------------------------------- 0.0/124.1 MB 2.0 MB/s eta 0:01:01
   ---------------------------------------- 0.1/124.1 MB 983.0 kB/s eta 0:02:07
   ---------------------------------------- 0.2/124.1 MB 1.2 MB/s eta 0:01:40
   ---------------------------------------- 0.3/124.1 MB 1.1 MB/s eta 0:01:50
   ---------------------------------------- 0.4/124.1 MB 1.6 MB/s eta 0:01:17
   ---------------------------------------- 0.5/124.1 MB 1.5 MB/s eta 0:01:22
   ---------------------------------------- 0.7/124.1 MB 2.1 MB/s eta 0:01:01
   ---------------------------------------- 1.0/124.1 MB 2.5 MB/s eta 0:00:49
   ---------------------------------------- 1.3/124.1 MB 2.8 MB/s eta 0:00:44
    --------------------------------------- 2.0/124.1 MB 4.0 MB/s eta 0:00:31
    --------------------------------------- 2.3/124.1 MB 4.2 MB/s eta 0:00:30
   - -------------------------------------- 3.4/124.1 MB 5.7 MB/s eta 0:00:22
   - -------------------------------------- 4.2/124.1 MB 6.7 MB/s eta 0:00:19
   - -------------------------------------- 6.0/124.1 MB 8.9 MB/s eta 0:00:14
   -- ------------------------------------- 8.0/124.1 MB 11.1 MB/s eta 0:00:11
   --- ------------------------------------ 9.6/124.1 MB 12.6 MB/s eta 0:00:10
   --- ------------------------------------ 11.5/124.1 MB 28.5 MB/s eta 0:00:04
   ---- ----------------------------------- 13.4/124.1 MB 36.4 MB/s eta 0:00:04
   ---- ----------------------------------- 15.1/124.1 MB 40.9 MB/s eta 0:00:03
   ----- ---------------------------------- 16.2/124.1 MB 38.5 MB/s eta 0:00:03
   ----- ---------------------------------- 16.2/124.1 MB 38.5 MB/s eta 0:00:03
   ----- ---------------------------------- 16.2/124.1 MB 38.5 MB/s eta 0:00:03
   ----- ---------------------------------- 16.2/124.1 MB 38.5 MB/s eta 0:00:03
   ----- ---------------------------------- 16.2/124.1 MB 38.5 MB/s eta 0:00:03
   ----- ---------------------------------- 17.7/124.1 MB 22.6 MB/s eta 0:00:05
   ----- ---------------------------------- 17.7/124.1 MB 22.6 MB/s eta 0:00:05
   ------ --------------------------------- 19.1/124.1 MB 19.3 MB/s eta 0:00:06
   ------ --------------------------------- 19.4/124.1 MB 19.8 MB/s eta 0:00:06
   ------ --------------------------------- 20.2/124.1 MB 17.2 MB/s eta 0:00:07
   ------ --------------------------------- 20.7/124.1 MB 17.2 MB/s eta 0:00:07
   ------ --------------------------------- 20.8/124.1 MB 15.6 MB/s eta 0:00:07
   ------- -------------------------------- 21.9/124.1 MB 15.2 MB/s eta 0:00:07
   ------- -------------------------------- 21.9/124.1 MB 15.2 MB/s eta 0:00:07
   ------- -------------------------------- 23.1/124.1 MB 13.6 MB/s eta 0:00:08
   ------- -------------------------------- 23.1/124.1 MB 13.6 MB/s eta 0:00:08
   ------- -------------------------------- 23.9/124.1 MB 12.6 MB/s eta 0:00:08
   ------- -------------------------------- 24.4/124.1 MB 12.4 MB/s eta 0:00:09
   ------- -------------------------------- 24.8/124.1 MB 11.5 MB/s eta 0:00:09
   -------- ------------------------------- 26.3/124.1 MB 11.7 MB/s eta 0:00:09
   -------- ------------------------------- 26.4/124.1 MB 13.9 MB/s eta 0:00:08
   -------- ------------------------------- 27.8/124.1 MB 13.6 MB/s eta 0:00:08
   --------- ------------------------------ 29.8/124.1 MB 16.8 MB/s eta 0:00:06
   ---------- ----------------------------- 31.3/124.1 MB 18.7 MB/s eta 0:00:05
   ---------- ----------------------------- 33.2/124.1 MB 21.8 MB/s eta 0:00:05
   ----------- ---------------------------- 35.0/124.1 MB 31.2 MB/s eta 0:00:03
   ----------- ---------------------------- 36.4/124.1 MB 29.7 MB/s eta 0:00:03
   ------------ --------------------------- 38.4/124.1 MB 38.5 MB/s eta 0:00:03
   ------------ --------------------------- 40.1/124.1 MB 36.3 MB/s eta 0:00:03
   ------------- -------------------------- 41.5/124.1 MB 36.4 MB/s eta 0:00:03
   -------------- ------------------------- 43.5/124.1 MB 36.4 MB/s eta 0:00:03
   -------------- ------------------------- 45.1/124.1 MB 36.4 MB/s eta 0:00:03
   --------------- ------------------------ 47.0/124.1 MB 36.4 MB/s eta 0:00:03
   --------------- ------------------------ 49.0/124.1 MB 38.6 MB/s eta 0:00:02
   ---------------- ----------------------- 50.6/124.1 MB 38.6 MB/s eta 0:00:02
   ---------------- ----------------------- 52.6/124.1 MB 40.9 MB/s eta 0:00:02
   ----------------- ---------------------- 54.1/124.1 MB 38.5 MB/s eta 0:00:02
   ------------------ --------------------- 56.0/124.1 MB 40.9 MB/s eta 0:00:02
   ------------------ --------------------- 57.8/124.1 MB 38.5 MB/s eta 0:00:02
   ------------------- -------------------- 59.5/124.1 MB 38.5 MB/s eta 0:00:02
   ------------------- -------------------- 61.1/124.1 MB 38.6 MB/s eta 0:00:02
   -------------------- ------------------- 62.8/124.1 MB 38.6 MB/s eta 0:00:02
   -------------------- ------------------- 64.5/124.1 MB 38.6 MB/s eta 0:00:02
   --------------------- ------------------ 66.2/124.1 MB 36.4 MB/s eta 0:00:02
   --------------------- ------------------ 67.9/124.1 MB 36.4 MB/s eta 0:00:02
   ---------------------- ----------------- 69.5/124.1 MB 36.4 MB/s eta 0:00:02
   ---------------------- ----------------- 71.2/124.1 MB 34.4 MB/s eta 0:00:02
   ----------------------- ---------------- 72.9/124.1 MB 36.3 MB/s eta 0:00:02
   ------------------------ --------------- 74.6/124.1 MB 36.4 MB/s eta 0:00:02
   ------------------------ --------------- 76.3/124.1 MB 36.3 MB/s eta 0:00:02
   ------------------------- -------------- 77.9/124.1 MB 36.3 MB/s eta 0:00:02
   ------------------------- -------------- 79.5/124.1 MB 36.4 MB/s eta 0:00:02
   -------------------------- ------------- 81.2/124.1 MB 36.4 MB/s eta 0:00:02
   -------------------------- ------------- 82.9/124.1 MB 36.4 MB/s eta 0:00:02
   --------------------------- ------------ 84.5/124.1 MB 36.4 MB/s eta 0:00:02
   --------------------------- ------------ 86.2/124.1 MB 36.4 MB/s eta 0:00:02
   ---------------------------- ----------- 87.8/124.1 MB 36.4 MB/s eta 0:00:01
   ---------------------------- ----------- 89.5/124.1 MB 36.3 MB/s eta 0:00:01
   ----------------------------- ---------- 91.2/124.1 MB 36.3 MB/s eta 0:00:01
   ----------------------------- ---------- 92.8/124.1 MB 36.4 MB/s eta 0:00:01
   ------------------------------ --------- 94.6/124.1 MB 36.4 MB/s eta 0:00:01
   ------------------------------- -------- 96.2/124.1 MB 36.4 MB/s eta 0:00:01
   ------------------------------- -------- 97.9/124.1 MB 36.4 MB/s eta 0:00:01
   -------------------------------- ------- 99.5/124.1 MB 36.4 MB/s eta 0:00:01
   ------------------------------- ------- 101.2/124.1 MB 38.6 MB/s eta 0:00:01
   -------------------------------- ------ 102.9/124.1 MB 36.4 MB/s eta 0:00:01
   -------------------------------- ------ 104.5/124.1 MB 36.4 MB/s eta 0:00:01
   --------------------------------- ----- 106.2/124.1 MB 36.4 MB/s eta 0:00:01
   --------------------------------- ----- 107.8/124.1 MB 36.3 MB/s eta 0:00:01
   ---------------------------------- ---- 109.5/124.1 MB 36.3 MB/s eta 0:00:01
   ---------------------------------- ---- 111.1/124.1 MB 36.4 MB/s eta 0:00:01
   ----------------------------------- --- 112.8/124.1 MB 36.4 MB/s eta 0:00:01
   ----------------------------------- --- 114.4/124.1 MB 36.4 MB/s eta 0:00:01
   ------------------------------------ -- 116.1/124.1 MB 36.4 MB/s eta 0:00:01
   ------------------------------------ -- 117.7/124.1 MB 36.4 MB/s eta 0:00:01
   ------------------------------------- - 119.3/124.1 MB 36.4 MB/s eta 0:00:01
   --------------------------------------  121.0/124.1 MB 38.5 MB/s eta 0:00:01
   --------------------------------------  122.6/124.1 MB 36.4 MB/s eta 0:00:01
   --------------------------------------  124.1/124.1 MB 36.4 MB/s eta 0:00:01
   --------------------------------------  124.1/124.1 MB 36.4 MB/s eta 0:00:01
   --------------------------------------  124.1/124.1 MB 36.4 MB/s eta 0:00:01
   --------------------------------------  124.1/124.1 MB 36.4 MB/s eta 0:00:01
   --------------------------------------  124.1/124.1 MB 36.4 MB/s eta 0:00:01
   --------------------------------------- 124.1/124.1 MB 16.8 MB/s eta 0:00:00
Downloading sentencepiece-0.2.2-cp311-cp311-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 38.6 MB/s eta 0:00:00
Downloading setuptools-84.0.0-py3-none-any.whl (818 kB)
   ---------------------------------------- 0.0/818.2 kB ? eta -:--:--
   --------------------------------------- 818.2/818.2 kB 50.5 MB/s eta 0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ------------ --------------------------- 1.9/6.3 MB 62.4 MB/s eta 0:00:01
   ----------------------- ---------------- 3.7/6.3 MB 47.9 MB/s eta 0:00:01
   ---------------------------------- ----- 5.4/6.3 MB 43.5 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 40.3 MB/s eta 0:00:00
Installing collected packages: sympy, setuptools, sentencepiece, torch
  Attempting uninstall: sympy
    Found existing installation: sympy 1.11.1
    Uninstalling sympy-1.11.1:
      Successfully uninstalled sympy-1.11.1
  Attempting uninstall: setuptools
    Found existing installation: setuptools 68.0.0
    Uninstalling setuptools-68.0.0:
      Successfully uninstalled setuptools-68.0.0
Successfully installed sentencepiece-0.2.2 setuptools-84.0.0 sympy-1.14.0 torch-2.14.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script isympy.exe is installed in 'D:\Anacondaupdate\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'D:\Anacondaupdate\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.41 requires requests_mock, which is not installed.
conda-repo-cli 1.0.41 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.41 requires nbformat==5.4.0, but you have nbformat 5.7.0 which is incompatible.
conda-repo-cli 1.0.41 requires python-dateutil==2.8.2, but you have python-dateutil 2.9.0.post0 which is incompatible.
conda-repo-cli 1.0.41 requires requests==2.28.1, but you have requests 2.31.0 which is incompatible.

In [ ]:
%pip uninstall -y torch
%pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu

Found existing installation: torch 2.14.1
Uninstalling torch-2.14.1:
  Successfully uninstalled torch-2.14.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
import sys
import torch

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print(torch.rand(2, 3))

D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\torch\_subclasses\functional_tensor.py:368: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))

Python: D:\Anacondaupdate\envs\sentiment311\python.exe
PyTorch: 2.14.1+cpu
tensor([[0.3558, 0.5866, 0.8108],
        [0.0481, 0.3664, 0.6864]])

In [2]:
%pip install numpy pandas google-play-scraper transformers sentencepiece tqdm jinja2

Collecting numpy
  Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting pandas
  Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
Collecting transformers
  Downloading transformers-5.18.0-py3-none-any.whl.metadata (32 kB)
Collecting sentencepiece
  Downloading sentencepiece-0.2.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting tqdm
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: jinja2 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from pandas) (2026.5)
Collecting huggingface-hub<3.0,>=1.31.0 (from transformers)
  Downloading huggingface_hub-2.1.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: packaging>=20.0 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers)
  Downloading regex-2026.9.29-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<0.24.0,>=0.23.1 (from transformers)
  Downloading tokenizers-0.23.2-cp310-abi3-win_amd64.whl.metadata (10 kB)
Collecting typer (from transformers)
  Downloading typer-0.27.2-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.8.0 (from transformers)
  Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<3.0,>=1.31.0->transformers)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (3.32.3)
Requirement already satisfied: fsspec>=2023.5.0 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2026.7.0)
Collecting hf-xet<2.0.0,>=1.6.0 (from huggingface-hub<3.0,>=1.31.0->transformers)
  Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx2<3,>=2.0.0 (from huggingface-hub<3.0,>=1.31.0->transformers)
  Downloading httpx2-2.13.1-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.16.0)
Requirement already satisfied: anyio>=4.10 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (4.15.1)
Collecting httpcore2==2.13.1 (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers)
  Downloading httpcore2-2.13.1-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: idna>=3.18 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.20)
Collecting truststore>=0.10 (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers)
  Downloading truststore-0.10.4-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: h11>=0.16 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from httpcore2==2.13.1->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Collecting huggingface-hub<3.0,>=1.31.0 (from transformers)
  Downloading huggingface_hub-1.33.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (0.28.1)
Requirement already satisfied: certifi in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (1.0.9)
Requirement already satisfied: colorama in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from jinja2) (3.0.3)
Requirement already satisfied: six>=1.5 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in D:\Anacondaupdate\envs\sentiment311\Lib\site-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.6 MB 7.9 MB/s eta 0:00:02
   ------------------------------- -------- 10.0/12.6 MB 20.0 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.6 MB 15.7 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 12.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 9.4 MB/s  0:00:01
Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------------- -------------------------- 3.4/9.9 MB 18.3 MB/s eta 0:00:01
   --------------- ------------------------ 3.9/9.9 MB 9.8 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.9 MB 8.4 MB/s eta 0:00:01
   ------------------- -------------------- 4.7/9.9 MB 5.8 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.9 MB 5.1 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.9 MB 4.5 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.9 MB 4.0 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 3.8 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.9 MB 3.6 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 3.5 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 3.3 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/9.9 MB 3.3 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.9 MB 3.1 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 3.1 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 3.0 MB/s  0:00:03
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Downloading transformers-5.18.0-py3-none-any.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------------- ------------------------- 4.5/12.6 MB 26.9 MB/s eta 0:00:01
   --------------- ------------------------ 4.7/12.6 MB 13.6 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.6 MB 10.2 MB/s eta 0:00:01
   ------------------- -------------------- 6.0/12.6 MB 8.0 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.6 MB 6.5 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 6.0 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.6 MB 5.6 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 5.3 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 5.0 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 4.9 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.6 MB 4.8 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 4.7 MB/s  0:00:02
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------ --------------------------- 1.3/4.0 MB 6.7 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 8.0 MB/s  0:00:00
Downloading tokenizers-0.23.2-cp310-abi3-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ----------------------------- ---------- 2.1/2.9 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 10.4 MB/s  0:00:00
Downloading huggingface_hub-1.33.0-py3-none-any.whl (846 kB)
   ---------------------------------------- 0.0/846.4 kB ? eta -:--:--
   ---------------------------------------- 846.4/846.4 kB 12.4 MB/s  0:00:00
Downloading sentencepiece-0.2.2-cp311-cp311-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 10.6 MB/s  0:00:00
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Downloading regex-2026.9.29-cp311-cp311-win_amd64.whl (280 kB)
Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Downloading typer-0.27.2-py3-none-any.whl (123 kB)
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: tqdm, shellingham, sentencepiece, safetensors, regex, numpy, mdurl, hf-xet, google-play-scraper, click, annotated-doc, pandas, markdown-it-py, rich, huggingface-hub, typer, tokenizers, transformers

   ----------------------------------------  0/18 [tqdm]
   -- -------------------------------------  1/18 [shellingham]
   ------ ---------------------------------  3/18 [safetensors]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ----------- ----------------------------  5/18 [numpy]
   ------------- --------------------------  6/18 [mdurl]
   ----------------- ----------------------  8/18 [google-play-scraper]
   -------------------- -------------------  9/18 [click]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   ------------------------ --------------- 11/18 [pandas]
   -------------------------- ------------- 12/18 [markdown-it-py]
   -------------------------- ------------- 12/18 [markdown-it-py]
   -------------------------- ------------- 12/18 [markdown-it-py]
   -------------------------- ------------- 12/18 [markdown-it-py]
   ---------------------------- ----------- 13/18 [rich]
   ---------------------------- ----------- 13/18 [rich]
   ---------------------------- ----------- 13/18 [rich]
   ---------------------------- ----------- 13/18 [rich]
   ---------------------------- ----------- 13/18 [rich]
   ---------------------------- ----------- 13/18 [rich]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   ------------------------------- -------- 14/18 [huggingface-hub]
   --------------------------------- ------ 15/18 [typer]
   --------------------------------- ------ 15/18 [typer]
   --------------------------------- ------ 15/18 [typer]
   ----------------------------------- ---- 16/18 [tokenizers]
   ------------------------------------- -- 17/18 [transformers]
   ------------------------------------- -- 17/18 [transformers]
   ------------------------------------- -- 17/18 [transformers]
   ------------------------------------- -- 17/18 [transformers]
   ------------------------------------- -- 17/18 [transformers]

In [3]:
import numpy as np
import pandas as pd
import torch
from transformers import pipeline

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("PyTorch:", torch.__version__)
print("Library siap untuk analisis sentimen.")

D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

NumPy: 2.4.6
Pandas: 3.0.6
PyTorch: 2.14.1+cpu
Library siap untuk analisis sentimen.

In [1]:
import numpy as np
import torch

print("NumPy:", np.__version__)
print("PyTorch:", torch.__version__)

print(torch.tensor([1.0, 2.0]).numpy())

NumPy: 2.4.6
PyTorch: 2.14.1+cpu
[1. 2.]

In [2]:
import pandas as pd

df_reviews = pd.read_pickle("google_play_reviews_1year.pkl")
df_extraction = pd.read_pickle("google_play_extraction_status.pkl")

competitors = dict(
    df_reviews[["Competitor", "App_ID"]]
    .drop_duplicates()
    .itertuples(index=False, name=None)
)

import re
from transformers import pipeline
from tqdm import tqdm
from IPython.display import display

D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
%pip install --force-reinstall --no-cache-dir "numpy==1.26.4"

Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.8/15.8 MB 7.2 MB/s eta 0:00:02
   ------------------- -------------------- 7.6/15.8 MB 16.8 MB/s eta 0:00:01
   ----------------------------- ---------- 11.5/15.8 MB 18.0 MB/s eta 0:00:01
   ----------------------------- ---------- 11.8/15.8 MB 14.2 MB/s eta 0:00:01
   ------------------------------- -------- 12.6/15.8 MB 12.1 MB/s eta 0:00:01
   --------------------------------- ------ 13.1/15.8 MB 10.7 MB/s eta 0:00:01
   ---------------------------------- ----- 13.6/15.8 MB 9.6 MB/s eta 0:00:01
   ------------------------------------- -- 14.7/15.8 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.8 MB 8.2 MB/s eta 0:00:01
   ---------------------------------------- 15.8/15.8 MB 7.7 MB/s  0:00:02
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.6
    Uninstalling numpy-2.4.6:
      Successfully uninstalled numpy-2.4.6
Successfully installed numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\~umpy'.
  You can safely remove it manually.

In [1]:
import numpy as np
import pandas as pd
import torch

print("NumPy:", np.__version__)
print("Lokasi NumPy:", np.__file__)
print("Pandas:", pd.__version__)

print(pd.Series(["bagus", None]).fillna(""))
print(torch.tensor([1.0, 2.0]).numpy())

NumPy: 1.26.4
Lokasi NumPy: D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\numpy\__init__.py
Pandas: 3.0.6
0    bagus
1
dtype: str
[1. 2.]

In [2]:
%pip install --force-reinstall --no-cache-dir "numpy==1.26.4" "pandas==2.2.3"

Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting pandas==2.2.3
  Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting python-dateutil>=2.8.2 (from pandas==2.2.3)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.2.3)
  Downloading pytz-2026.5-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas==2.2.3)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.2.3)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.5/15.8 MB 14.0 kB/s eta 0:18:10
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32
   - -------------------------------------- 0.8/15.8 MB 21.7 kB/s eta 0:11:32

  WARNING: Failed to remove contents in a temporary directory 'D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\~-mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\~-mpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\~andas.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\~andas'.
  You can safely remove it manually.

In [1]:
import numpy as np
import pandas as pd
import torch

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print(pd.Series(["bagus", None]).fillna(""))
print(torch.tensor([1.0, 2.0]).numpy())

NumPy: 1.26.4
Pandas: 2.2.3
0    bagus
1
dtype: object
[1. 2.]

In [3]:
import sys
import subprocess
from pathlib import Path

# Environment sementara untuk membaca pickle Pandas 3
converter_dir = Path.cwd() / "pickle_converter"
converter_python = converter_dir / "Scripts" / "python.exe"

if not converter_python.exists():
    subprocess.check_call([
        sys.executable, "-m", "venv", str(converter_dir)
    ])

subprocess.check_call([
    str(converter_python), "-m", "pip", "install",
    "pandas>=3,<4", "numpy>=2,<3",
    "--disable-pip-version-check"
])

# Konversi tanpa mengubah file pickle asli
conversion_code = """
import pandas as pd
import sys

df = pd.read_pickle(sys.argv[1])
df.to_csv(sys.argv[2], index=False, encoding="utf-8-sig")
print(f"Berhasil konversi {len(df):,} review ke CSV.")
"""

subprocess.check_call([
    str(converter_python),
    "-c", conversion_code,
    str(Path("google_play_reviews_1year.pkl").resolve()),
    str(Path("google_play_reviews_1year.csv").resolve()),
])

0

In [4]:
import pandas as pd

df_reviews = pd.read_csv(
    "google_play_reviews_1year.csv",
    keep_default_na=False
)

print("Jumlah review:", len(df_reviews))
display(df_reviews[["Competitor", "content"]].head())

Jumlah review: 23394

  Competitor                                            content
0      Ajaib  sebaiknya broker memberikan laporan kepemilika...
1      Ajaib  kenapa saya kasih ranting 1 ,akun pasword suda...
2      Ajaib  penarikan saldo.. super paling lama...dari pen...
3      Ajaib                                      mudah diikuti
4      Ajaib                                              bagus

In [6]:
df_reviews = pd.read_csv(
    "google_play_reviews_1year.csv",
    keep_default_na=False
)

In [7]:
# =====================================================
# 1. IMPORT LIBRARY
# =====================================================
import re
import pandas as pd
from transformers import pipeline
from tqdm import tqdm
from IPython.display import display

# =====================================================
# 2. BACA REVIEW DAN FILTER PERIODE
# =====================================================
df_reviews = pd.read_csv(
    "google_play_reviews_1year.csv",
    keep_default_na=False
)

start_date = pd.Timestamp("2025-10-06 00:00:00")
end_date = pd.Timestamp("2026-10-06 09:39:00")

df_reviews["at"] = pd.to_datetime(
    df_reviews["at"], errors="coerce"
)

df_reviews = df_reviews.loc[
    df_reviews["at"].between(start_date, end_date)
].copy().reset_index(drop=True)

if df_reviews.empty:
    raise ValueError("Tidak ada review dalam periode yang dipilih.")

print("Period: 06 October 2025 – 06 October 2026, 09:39")
print(f"Reviews collected: {len(df_reviews):,}")

# =====================================================
# 3. SIAPKAN MODEL RoBERTa
# =====================================================
model_name = "w11wo/indonesian-roberta-base-sentiment-classifier"

model = pipeline(
    "sentiment-analysis",
    model=model_name,
    tokenizer=model_name,
    framework="pt",
    device=-1,  # CPU
)

print("Model labels:", model.model.config.id2label)

def normalize_label(label):
    label = str(label).strip().lower()

    if label.startswith("label_"):
        label_id = int(label.split("_")[-1])
        label = str(model.model.config.id2label[label_id]).lower()

    label_map = {
        "positive": "Positive",
        "neutral": "Neutral",
        "negative": "Negative",
    }

    if label not in label_map:
        raise ValueError(f"Label tidak dikenali: {label}")

    return label_map[label]

# =====================================================
# 4. ANALISIS TEKS REVIEW
# =====================================================
df_sentiment = df_reviews.copy()

df_sentiment["Review_Text"] = (
    df_sentiment["content"].fillna("").astype(str).str.strip()
)

df_sentiment["Text_Sentiment"] = pd.Series(
    pd.NA, index=df_sentiment.index, dtype="string"
)
df_sentiment["Model_Score"] = float("nan")

valid_text = df_sentiment["Review_Text"].ne("")

# Teks identik diproses sekali, lalu dipetakan ke setiap review.
texts = (
    df_sentiment.loc[valid_text, "Review_Text"]
    .drop_duplicates()
    .tolist()
)

batch_size = 16
lookup = {}

for start in tqdm(
    range(0, len(texts), batch_size),
    desc="RoBERTa sentiment"
):
    batch = texts[start:start + batch_size]

    results = model(
        batch,
        batch_size=batch_size,
        truncation=True,
        max_length=512,
    )

    for text, result in zip(batch, results):
        lookup[text] = (
            normalize_label(result["label"]),
            float(result["score"]),
        )

df_sentiment.loc[valid_text, "Text_Sentiment"] = (
    df_sentiment.loc[valid_text, "Review_Text"]
    .map(lambda text: lookup[text][0])
)

df_sentiment.loc[valid_text, "Model_Score"] = (
    df_sentiment.loc[valid_text, "Review_Text"]
    .map(lambda text: lookup[text][1])
)

# Simpan prediksi sebelum membuat tabel.
df_sentiment.to_csv(
    "google_play_roberta_detail.csv",
    index=False,
    encoding="utf-8-sig"
)

# =====================================================
# 5. TEMA PADA REVIEW YANG DIPREDIKSI NEGATIF
# =====================================================
# Tema memakai kata kunci, bukan klasifikasi tema oleh RoBERTa.
complaint_patterns = {
    "Login / account access": (
        r"\blogin\b|\blog in\b|\botp\b|\bpassword\b|"
        r"\bpin\b|\blogout\b|\btidak bisa masuk\b"
    ),
    "App stability / speed": (
        r"\blemot\b|\blambat\b|\blag\b|\bhang\b|"
        r"\bcrash\b|\bforce close\b|\berror\b|"
        r"\bbug\b|\bloading\b|\bmacet\b"
    ),
    "Trading / order execution": (
        r"\border\b|\bpesanan\b|\btransaksi\b|"
        r"\bjual\b|\bbeli\b|\btrading\b"
    ),
    "Deposit / withdrawal": (
        r"\bdeposit\b|\bwithdraw\w*\b|\bpenarikan\b|"
        r"\btransfer\b|\bsaldo\b|\brdn\b|\btop up\b"
    ),
    "Customer support": (
        r"\bcs\b|\bcustomer service\b|\bsupport\b|"
        r"\blayanan pelanggan\b|\bkomplain\b"
    ),
    "Charts / market data": (
        r"\bchart\b|\bgrafik\b|\bdata\b|"
        r"\brealtime\b|\breal time\b|\bquote\b"
    ),
}

def identify_themes(text):
    return "; ".join(
        theme
        for theme, pattern in complaint_patterns.items()
        if re.search(pattern, text, flags=re.IGNORECASE)
    )

df_sentiment["Complaint_Themes"] = ""

negative_mask = (
    df_sentiment["Text_Sentiment"].eq("Negative").fillna(False)
)

df_sentiment.loc[negative_mask, "Complaint_Themes"] = (
    df_sentiment.loc[negative_mask, "Review_Text"]
    .map(identify_themes)
)

# =====================================================
# 6. TABEL RINGKASAN PER APLIKASI
# =====================================================
rows = []

for app_name, group in df_sentiment.groupby(
    "Competitor", sort=False
):
    analyzed = group.loc[group["Text_Sentiment"].notna()]
    n = len(analyzed)

    negative_texts = analyzed.loc[
        analyzed["Text_Sentiment"].eq("Negative"),
        "Review_Text"
    ]

    theme_counts = {
        theme: int(
            negative_texts.str.contains(
                pattern, case=False, regex=True, na=False
            ).sum()
        )
        for theme, pattern in complaint_patterns.items()
    }

    highest = max(theme_counts.values(), default=0)

    top_theme = (
        " / ".join(
            theme for theme, count in theme_counts.items()
            if count == highest
        )
        if highest > 0
        else "No matching keyword theme"
    )

    rows.append({
        "App": app_name,
        "Reviews Collected": len(group),
        "Texts Analyzed": n,
        "Avg Review Rating": pd.to_numeric(
            group["score"], errors="coerce"
        ).mean(),
        "Positive %": (
            analyzed["Text_Sentiment"].eq("Positive").mean() * 100
            if n else None
        ),
        "Neutral %": (
            analyzed["Text_Sentiment"].eq("Neutral").mean() * 100
            if n else None
        ),
        "Negative %": (
            analyzed["Text_Sentiment"].eq("Negative").mean() * 100
            if n else None
        ),
        "Top Complaint Theme": top_theme if n else "N/A",
        "Theme Mentions": highest if n else None,
    })

df_text_summary = pd.DataFrame(rows)

display(
    df_text_summary.style
    .hide(axis="index")
    .format({
        "Reviews Collected": "{:,.0f}",
        "Texts Analyzed": "{:,.0f}",
        "Avg Review Rating": "{:.2f}",
        "Positive %": "{:.1f}%",
        "Neutral %": "{:.1f}%",
        "Negative %": "{:.1f}%",
        "Theme Mentions": "{:,.0f}",
    }, na_rep="N/A")
)

# =====================================================
# 7. SIMPAN HASIL DAN TAMPILKAN SAMPEL
# =====================================================
df_sentiment.to_csv(
    "google_play_roberta_detail.csv",
    index=False,
    encoding="utf-8-sig"
)

df_text_summary.to_csv(
    "google_play_roberta_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

samples = []

for _, group in df_sentiment.loc[
    df_sentiment["Text_Sentiment"].notna()
].groupby(["Competitor", "Text_Sentiment"]):
    samples.append(
        group.sample(n=min(3, len(group)), random_state=42)
    )

if samples:
    print("\nSAMPLE REVIEWS — CHECK PREDICTIONS")

    display(
        pd.concat(samples, ignore_index=True)[
            [
                "Competitor",
                "Review_Text",
                "Text_Sentiment",
                "Model_Score",
                "Complaint_Themes",
            ]
        ]
    )

print("\nSELESAI. Hasil detail dan tabel ringkasan tersimpan.")

D:\Anacondaupdate\envs\sentiment311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Period: 06 October 2025 – 06 October 2026, 09:39
Reviews collected: 23,394

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 599.12it/s]

Model labels: {0: 'positive', 1: 'neutral', 2: 'negative'}

RoBERTa sentiment: 100%|██████████| 1273/1273 [13:34<00:00,  1.56it/s]

SAMPLE REVIEWS — CHECK PREDICTIONS

,Competitor,Review_Text,Text_Sentiment,Model_Score,Complaint_Themes
0,Ajaib,masih nyoba dan belajar,Negative,0.603097,
1,Ajaib,verifikasi gua lamaa amat,Negative,0.981554,
2,Ajaib,perhari ini udah 12 jam layanan penarikan rdn ...,Negative,0.983919,Deposit / withdrawal
3,Ajaib,tolong di permudah prosesnya,Neutral,0.541340,
4,Ajaib,"mudah diikuti "" alim937 """,Neutral,0.993269,
5,Ajaib,aplikasi trading yang ok,Neutral,0.952323,
6,Ajaib,pengalaman mantap dan bagus sekali di Ajaib un...,Positive,0.996814,
7,Ajaib,"Benar benar Ajaib, semenjak download apl ini, ...",Positive,0.967450,
8,Ajaib,sudah lama pake ajaib dan selama ini gak ada m...,Positive,0.993479,
9,IPOT,saya pengguna baru. mau masuk akun gak bisa. p...,Negative,0.997647,
10,IPOT,"kenapa tidak bisa dipencet"" pilihan menu nya?",Negative,0.956871,
11,IPOT,"Semakin diupdet bikin user semakin kudet, kaya...",Negative,0.998712,Trading / order execution
12,IPOT,good aplikasi,Neutral,0.905381,
13,IPOT,kesulitan waktu portofolio dibuka di windows,Neutral,0.969016,
14,IPOT,"NICE bisa ikut E-IPO, semoga tampilannya diper...",Neutral,0.543356,
15,IPOT,ipot sekuritas saham yg baik .. fitur yg kompl...,Positive,0.982621,
16,IPOT,Aplikasi ini benar-benar mempermudah hidup say...,Positive,0.996512,
17,IPOT,responnya cepet untuk penggunaan aplikasi ipot...,Positive,0.990098,
18,KISI (KOINS Mobile),untuk versi pc bid offer nya nge lag dan eror ...,Negative,0.481733,App stability / speed
19,KISI (KOINS Mobile),ko saya abis ganti HP koins mobile ga bisa dib...,Negative,0.837968,
20,KISI (KOINS Mobile),kenapa withdrawl ke rekening pribadi lama seka...,Negative,0.992779,Deposit / withdrawal
21,KISI (KOINS Mobile),aplikasi kocak dan curang,Neutral,0.473695,
22,KISI (KOINS Mobile),tolong pihak koins upgrade apk nya supaya peng...,Neutral,0.701970,
23,KISI (KOINS Mobile),gabisa dibuka min,Neutral,0.973843,
24,KISI (KOINS Mobile),"Ada error disaat momen bagus, sangat disayang ...",Positive,0.538438,
25,KISI (KOINS Mobile),belajar saham dari kisi semarang dan ngerti sa...,Positive,0.721743,
26,KISI (KOINS Mobile),apk paling okk,Positive,0.894865,
27,KISI (iKISI),trading balance gak bisa ditarik..ada saldonya...,Negative,0.953941,Trading / order execution; Deposit / withdrawal
28,KISI (iKISI),daftar ya susah gimna ij cara daftar ia,Negative,0.989054,
29,KISI (iKISI),kenapa fitur broker summary nya yang menunjuka...,Negative,0.981202,
30,KISI (iKISI),"pemula hadir, semoga beruntung di investasi le...",Neutral,0.880778,
31,KISI (iKISI),gak ada top gainer time frame kecil seperti to...,Neutral,0.584990,
32,KISI (iKISI),sedikan fitur GTC order dong,Neutral,0.546929,
33,KISI (iKISI),"Aplikasi investasi yg luar biasa, tampilannya ...",Positive,0.997348,
34,KISI (iKISI),"Semua OK dari segi tampilan, performa dan laya...",Positive,0.968024,
35,KISI (iKISI),keren sekali apknya mudah diakses dan cocok un...,Positive,0.996153,
36,Mirae Asset (Neo HOTS),"Agustus 2020 Gak merasa beli BEKS, tapi BEKS t...",Negative,0.496821,Trading / order execution
37,Mirae Asset (Neo HOTS),Hadeh disuruh ganti password terus. Lama kelam...,Negative,0.998002,Login / account access
38,Mirae Asset (Neo HOTS),habis di update aku sampe sekarang gk bisa log...,Negative,0.978874,Login / account access
39,Mirae Asset (Neo HOTS),chart selalu berubah settingan nya,Neutral,0.867547,
40,Mirae Asset (Neo HOTS),mudah digunakan dan informatif,Neutral,0.709840,
41,Mirae Asset (Neo HOTS),bisa ditambahkan dalam menu order. pasang posi...,Neutral,0.916270,
42,Mirae Asset (Neo HOTS),aplikasi trading terbaik. chartnya juara sih. ...,Positive,0.993283,
43,Mirae Asset (Neo HOTS),"aplikasi ter ribet dan fee yg ga ngotak, dilih...",Positive,0.970501,
44,Mirae Asset (Neo HOTS),"Saya suka dg fiturnya, familiar dan mudah di a...",Positive,0.854829,
45,Stockbit,2 hari ngeleg parah erorrrr,Negative,0.998955,
46,Stockbit,like it,Negative,0.858689,
47,Stockbit,pagi ini kok bad sekali ..gak bisa liat detail...,Negative,0.998686,
48,Stockbit,Semoga beruntung,Neutral,0.701759,
49,Stockbit,sudah bisa,Neutral,0.969782,
50,Stockbit,man tappp,Neutral,0.845037,
51,Stockbit,lumayan bagus jarang kendala kedepannya bisa l...,Positive,0.991948,
52,Stockbit,gak bisa berkata-kata. terlepas kelebihan dan ...,Positive,0.988017,
53,Stockbit,"sejauh ini lancar lancar aja sih,sukses kedepa...",Positive,0.986477,

SELESAI. Hasil detail dan tabel ringkasan tersimpan.

In [8]:
print(df_sentiment.columns.tolist())

['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion', 'Competitor', 'App_ID', 'Review_Text', 'Text_Sentiment', 'Model_Score', 'Complaint_Themes']

In [9]:
pd.set_option("display.max_colwidth", None)

display(
    df_sentiment.sample(
        n=min(30, len(df_sentiment)),
        random_state=42
    )
)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,Competitor,App_ID,Review_Text,Text_Sentiment,Model_Score,Complaint_Themes
13103,12a2e86b-019d-4a84-9137-fd757d250f86,Lukman Hakim,https://play-lh.googleusercontent.com/a-/ALV-UjU5x8ezKpeOGJBBd83i5ZJYHdBqWBEdOT82oyHxEyKZZ-4_ATy6,good,5,0,2.88.0,2026-01-16 10:56:02,,,2.88.0,Ajaib,ajaib.co.id,good,Positive,0.742257,
3256,00636e23-86dc-4b1c-bb6a-a544b561f356,nigel hashemian ahmad,https://play-lh.googleusercontent.com/a-/ALV-UjWLY-lLVdS_kLUQfvqh33DFU8Bux6Psd-Ni2VhWJNQoiOFe1MQN,sangat mudah trading saham di ajaib,5,0,2.100.0,2026-06-25 03:53:52,"Makasih ya, Kak! 💙 Semoga pengalaman investasi bersama Ajaib selalu menyenangkan. Kami akan terus berusaha memberikan layanan yang semakin baik.✨ -AJ\n",2026-08-02 05:41:48,2.100.0,Ajaib,ajaib.co.id,sangat mudah trading saham di ajaib,Positive,0.753554,
8081,ba91e21c-c98e-4be6-b156-94ab074d3865,Nunik Silviana,https://play-lh.googleusercontent.com/a/ACg8ocKUwloSSvOxBz__JfivbAUbZi4GKXdcpdXQ3m1bpXX3Q8RqpQ=mo,sangat mudah untuk trader baru seperti saya. mudah melihat chart candle ma macd jual beli fast trade. cara buka akun juga sangat mudah. tidak punya tabungan juga bisa nabung di ajaibnya. sangat rekomended buat ritel unyu2 seperti sayah.,5,0,,2026-05-09 09:38:03,"Terima kasih banyak, Kak! 💙 Senang banget bisa menemani perjalanan investasi Kakak. Semoga selalu lancar dan cuan terus bareng Ajaib! ✨ ~YOH",2026-05-19 09:29:07,,Ajaib,ajaib.co.id,sangat mudah untuk trader baru seperti saya. mudah melihat chart candle ma macd jual beli fast trade. cara buka akun juga sangat mudah. tidak punya tabungan juga bisa nabung di ajaibnya. sangat rekomended buat ritel unyu2 seperti sayah.,Positive,0.995868,
18041,94874256-982b-47cb-b547-6e5e7150a8c3,Reza Pecoc,https://play-lh.googleusercontent.com/a-/ALV-UjVtdedTeY-r5xmdgYBS5QS2yTG_7LaypcOIgl1FSTVlSNIqIb-ONQ,broker andalan retail 👍🏻,5,0,3.20.0,2026-04-17 18:34:03,"Halo kak,\n\nSenangnya baca review positif dari Kakak. Kami akan terus berupaya untuk memberikan pengalaman yang baik untuk Kakak. Jika ada saran silakan dapat kirimkan ke kami melalui email ke support@stockbit.com atau kakak bisa klik menu Chat Support di aplikasi Stockbit.\n\nTerima kasih dan semoga hari kakak menyenangkan! ☺️\n",2026-04-20 16:13:45,3.20.0,Stockbit,com.stockbit.android,broker andalan retail 👍🏻,Neutral,0.514604,
17991,4cfbd75c-0e62-4e99-bddc-38f973e8ffc7,Mendy Bawias,https://play-lh.googleusercontent.com/a-/ALV-UjW-ebxDmZ8d-ZZ-dRupQPZWfxEQgv5D_KdPSfKAMgkyyOuWv4rm,terbaik ui dan ux,5,0,3.19.7,2026-04-17 18:35:35,"Halo kak,\n\nSenang sekali baca review positif dari Kakak. Jangan lupa rekomendasikan ke teman-teman kakak yang lain ya ☺️Jika ada saran, silakan dapat kirimkan ke kami melalui email ke support@stockbit.com atau kakak bisa klik menu Chat Support di aplikasi Stockbit.\n\nSemoga harinya menyenangkan!😆\n",2026-04-20 16:51:41,3.19.7,Stockbit,com.stockbit.android,terbaik ui dan ux,Positive,0.950522,
5584,df0b8679-6c97-491c-ada0-f0ba1660fa99,Aditya Afan,https://play-lh.googleusercontent.com/a-/ALV-UjUzE4PKQ7MOTVAYdasX_rOoVZ939vKNZNLBcP0ZCeXrKRiALjI,bisa belajar investasi,5,0,,2026-05-23 13:11:41,"Hai Kak Afan, terima kasih atas bintang 5-nya! 🙏 Senang mendengar Kakak nyaman berinvestasi bersama Ajaib. Ingat, kalau ada pertanyaan soal produk atau butuh bantuan navigasi, Bantuan Ajaib siap membantu kapan pun ya! Semangat terus! 💪 ~YOH",2026-05-25 11:11:41,,Ajaib,ajaib.co.id,bisa belajar investasi,Neutral,0.833369,
221,5e7c0bb8-7f78-44f7-a162-be891dd7e371,Fenny Irawaty,https://play-lh.googleusercontent.com/a/ACg8ocITixxElQRv08LucQ-V03D9v5shasTLv5Cw5qOj-NBy8EfSeQ=mo,"cocok untuk pemula, mudah di pahami, informasi lengkap",5,0,2.105.3,2026-09-10 10:41:34,"Makasih banyak, Kak! 💫 Kami senang bisa jadi bagian dari perjalanan investasi Kakak. Sukses terus untuk langkah investasinya ya! -GN",2026-09-10 12:05:18,2.105.3,Ajaib,ajaib.co.id,"cocok untuk pemula, mudah di pahami, informasi lengkap",Positive,0.750598,
11400,b35197e9-49c2-40ce-819a-bc9e03109772,Cipta Anugrah,https://play-lh.googleusercontent.com/a-/ALV-UjXDJzF3PLU85DTb5hWsSvv7qhJZLBDF-j4-U0YL_aTlMNRyMYY,best investasi,5,0,2.93.0,2026-03-28 09:04:52,,,2.93.0,Ajaib,ajaib.co.id,best investasi,Neutral,0.836444,
8743,1ba45529-a2c7-4ebc-be87-835259d118a0,Bima Hakim,https://play-lh.googleusercontent.com/a-/ALV-UjXh7Wd9ZmNeRdiBJpfprAVH7lgBFuyueL1A_P57mB-bbDS-lGA,"walau baru pakai ajaib, tapi untuk menu dan informasi nya mudah untuk dimengerti, dan sudah ada beberapa kali profit walau masih kecil tapi pasti, semoga ajaib bisa jadi lebih baik lagi",5,0,2.96.0,2026-05-07 00:45:28,"Wah Kak, makasih sudah memulai perjalanan investasinya bersama Ajaib! 😊 Kami senang bisa jadi teman investasi Kakak. Jangan ragu untuk bertanya atau hubungi Bantuan Ajaib kalau butuh panduan ya – kami selalu ada! 🌟 ~YOH",2026-05-07 16:47:40,2.96.0,Ajaib,ajaib.co.id,"walau baru pakai ajaib, tapi untuk menu dan informasi nya mudah untuk dimengerti, dan sudah ada beberapa kali profit walau masih kecil tapi pasti, semoga ajaib bisa jadi lebih baik lagi",Positive,0.993334,
19912,03fc2273-8e89-4610-bf21-4857c6d348fa,Bagus Rakha,https://play-lh.googleusercontent.com/a-/ALV-UjUa5V_jsz2h9e7Ed3Zq4L4ZagIMTQn6U_BIMDfjMHyK1M0o8qLM,sedang belajar inves apk ini insyaAllah cocok untuk pemula yang akan belajar investasi,5,0,3.17.3,2025-12-28 15:06:00,"Halo kak Bagus Rakha,\n\nSenang sekali baca review positif dari Kakak. Jangan lupa rekomendasikan ke teman-teman kakak yang lain ya :) Jika ada saran, silakan dapat kirimkan ke kami melalui email ke support@stockbit.com atau kakak bisa klik menu Chat Support di aplikasi Stockbit.\n\nSemoga harinya menyenangkan!",2025-12-29 15:31:16,3.17.3,Stockbit,com.stockbit.android,sedang belajar inves apk ini insyaAllah cocok untuk pemula yang akan belajar investasi,Neutral,0.401501,
16080,8d4598c2-d352-4079-99ef-d3bf9cff4deb,Jatra Succes,https://play-lh.googleusercontent.com/a/ACg8ocI9Z--j2gynZe5XkIXqQHPvP0drhUsEIluyTvilCkLeFbA_vw=mo,Jangan ragu untuk coba ini. Keren,5,0,3.22.1,2026-08-06 16:33:44,"Halo Kak Jatra Succes,\n\nTerima kasih atas review baiknya. Silakan rekomendasikan ke teman-teman Kakak agar mereka juga merasakan pengalamannya 🙌 Jika ada masukan atau kendala, jangan ragu hubungi Chat Support di aplikasi.\n\nSemangat selalu dan semoga harinya menyenangkan! 🚀",2026-08-06 16:42:58,3.22.1,Stockbit,com.stockbit.android,Jangan ragu untuk coba ini. Keren,Positive,0.993599,
23360,5daa7d40-0041-4cc6-8c85-f8e0930a07b0,Ilham,https://play-lh.googleusercontent.com/a-/ALV-UjU1QdUndAJWUhEeeEhAYhTjQ7Yzv74XT1BC90XQa3iWV5_8G8Q,"fiturnya mantaap, semoga kedepannya lebih lengkap lagi",5,0,1.4.0,2025-11-03 16:43:04,,,1.4.0,KISI (iKISI),com.koreainvestment.indonesia,"fiturnya mantaap, semoga kedepannya lebih lengkap lagi",Positive,0.946421,
8054,9919d820-0ea1-4019-a065-b810a34e0ba1,jaeni dahlan,https://play-lh.googleusercontent.com/a-/ALV-UjUCOdaSDApaiDFk4TMsuIk7R8bGt4HzJR05mLO1mWzu8yGj17Sy,mantaf,5,0,2.95.0,2026-05-09 11:45:25,"Wah, terima kasih banyak, Kak! ⭐️ Review dari Kakak bikin tim kami makin semangat. Semoga investasi Kakak selalu lancar ya! 📈 ~YOH",2026-05-18 17:10:57,2.95.0,Ajaib,ajaib.co.id,mantaf,Neutral,0.850814,
167,4bbdb432-a83b-46d8-ad76-213ad9acf172,Naufal Fadhil,https://play-lh.googleusercontent.com/a-/ALV-UjUWU9bqMvdpHD-kdASWdTLJNVqbwc6D90pBB8PJG37qQfrW2TVx,aplikasi banyak bug!!! sering banyak masalah,5,0,2.105.3,2026-09-15 14:15:28,"Halo Kak, kami minta maaf banget. Cerita dan keluhan Kakak penting untuk kami supaya bisa kami perbaiki. Yuk hubungi Bantuan Ajaib via chat Pusat Bantuan atau email resmi kami – tim siap bantu Kakak secepatnya! -GN",2026-09-15 14:17:08,2.105.3,Ajaib,ajaib.co.id,aplikasi banyak bug!!! sering banyak masalah,Negative,0.997905,App stability / speed
1427,8903958a-e2db-4e33-96fc-d522ce1abe6a,Habibi Nugroho,https://play-lh.googleusercontent.com/a/ACg8ocJt5Qc9MgtMAosoMdiHufYHSZEMjPbwvkcBxPeoKm1vKY5rSg=mo,Punya saya kok bloem dapat verifikasi email ya ? Pdhl email saya sdh benar trus saya sdh mintk kirim ulang berkali2 tp tetp saja tidak ada verifikasi ke email saya? Mohon bantuan nya,5,0,2.102.0,2026-07-28 19:16:27,"Hai Kak, mohon maaf buat keluhan yang Kakak alami. Kami benar-benar ingin tahu lebih lanjut agar bisa membantu. Boleh ceritakan kendalanya ke Bantuan Ajaib via chat Pusat Bantuan atau email support.saham@ajaib.co.id? Tim kami siap mendengar dan membantu! 🙏 -GN",2026-08-12 10:23:52,2.102.0,Ajaib,ajaib.co.id,Punya saya kok bloem dapat verifikasi email ya ? Pdhl email saya sdh benar trus saya sdh mintk kirim ulang berkali2 tp tetp saja tidak ada verifikasi ke email saya? Mohon bantuan nya,Negative,0.953864,
4579,271efaf7-e525-49b1-b407-133b55fc6c99,Hadi Perdana,https://play-lh.googleusercontent.com/a/ACg8ocKOBF4JiAoGNqA_cFTNx_mbkZYv3nZy_71ArFgesu0GF-tZpA=mo,apk nya kenapa gak bisa di buka ada apa ini kenapa gak ada pemberitahuan,4,0,2.98.1,2026-06-06 09:58:51,"Hai Kak, 4 bintang! Terima kasih ya 😊 Untuk kendala aplikasi, coba restart aplikasi dan pastikan internet stabil. Kalau masih muncul, chat Bantuan Ajaib di Pusat Bantuan dengan detail perangkat Kakak agar tim teknis kami bantu cek! 💙 ~YOH",2026-06-29 12:34:23,2.98.1,Ajaib,ajaib.co.id,apk nya kenapa gak bisa di buka ada apa ini kenapa gak ada pemberitahuan,Negative,0.934093,
13282,727fa978-919f-4fbf-9989-dbf105a12ed8,Dika Maisa,https://play-lh.googleusercontent.com/a/ACg8ocLAtYOYqpgFQreK4UAI9iF6eYo0T12cK6tvN2daAXvpU3qwbA=mo,"Pengalaman Saya, Saya sudah cancel stoploss, dan di menu auto order sudah tidak ada, namun saham saya terjual dan saya malah menjadi rugi. Baiknya pakai aplikasi yang lain saja semuanya. Terima kasih.",1,16,2.88.0,2026-01-12 13:33:39,"Hi kak,mohon maaf atas kendal yang kakak alami,dapat kami informasikan bahwasannya terkait kendala kakak dibutuhkan pengecekan lebih lanjut oleh tim kami. Mohon kesediaannya untuk menghubungi kami melalui Chat Bantuan Ajaib pada aplikasi atau melalui email kami di support.saham@ajaib.co.id Terima kasih ~AJ",2026-01-12 15:15:45,2.88.0,Ajaib,ajaib.co.id,"Pengalaman Saya, Saya sudah cancel stoploss, dan di menu auto order sudah tidak ada, namun saham saya terjual dan saya malah menjadi rugi. Baiknya pakai aplikasi yang lain saja semuanya. Terima kasih.",Negative,0.973132,Trading / order execution
6289,cda257ec-f9aa-415c-83d0-4df1b79763ae,Zain Oktavian,https://play-lh.googleusercontent.com/a-/ALV-UjUhIOFYAE9Q0Laf1adDisF34cje8N3KoPV2e3tbZbBSNYpgV2A,"tampilan fitur mudah, tp ad beberapa fitur yg tdk bisa saya gunakan seperti tabungan ajaib🙏",5,0,2.97.1,2026-05-17 22:06:01,"Hai Kak, terima kasih atas reviewnya yang jujur dan positif! 😊 Yuk hubungi Bantuan Ajaib via chat Pusat Bantuan atau email resmi kami – tim siap bantu Kakak secepatnya! ~TRI",2026-05-26 04:31:04,2.97.1,Ajaib,ajaib.co.id,"tampilan fitur mudah, tp ad beberapa fitur yg tdk bisa saya gunakan seperti tabungan ajaib🙏",Positive,0.777531,
16171,d20d82b3-ae20-4d4e-aaaf-7391b2d05188,madi king promotion,https://play-lh.googleusercontent.com/a/ACg8ocIdkUYast9PYGddxH-vgCFrVYROvw9v32R0omlrJE1b3mo6tw=mo,bagus,5,0,3.21.9,2026-07-24 20:23:32,"Halo kak Madi King Promotion,\n\nSenangnya membaca review positif dari Kakak. Kami akan terus berupaya untuk memberikan pengalaman yang baik untuk Kakak. Jika ada saran silakan dapat kirimkan ke kami melalui email ke support@stockbit.com atau kakak bisa klik menu Chat Support di aplikasi Stockbit.\n\nTerima kasih dan semoga hari kakak menyenangkan!",2026-07-27 08:44:03,3.21.9,Stockbit,com.stockbit.android,bagus,Positive,0.705738,
3463,a84684a7-1dfc-4059-bca1-cf8cafce5755,Anak Picing,https://play-lh.googleusercontent.com/a-/ALV-UjUk6MrjGJ9lbVoLSy1xkbb22gdQQOZQc1GhcCHpjRvu4XFLdOQ,lumayan bagus,5,0,2.99.1,2026-06-24 08:02:16,"Terima kasih banyak, Kak! 🌟 Support dari Kakak sangat berarti untuk kami. Semoga Ajaib bisa terus menemani perjalanan investasi Kakak ke depannya 💙 ~YOH",2026-07-23 12:57:15,2.99.1,Ajaib,ajaib.co.id,lumayan bagus,Positive,0.996216,
15008,87398a9f-6ef4-4e84-87d1-c28a547f8dc4,Samsung A03,https://play-lh.googleusercontent.com/a/ACg8ocIeBIe2mqg4eZoH-nGMRKCCSIg8PhxX73nuAXZLkp3hqQuRzA=mo,witdhraw lama saya beli token pame Whiz cuma 100rb udah 2 hari gak masuk² tolong lah bantu woi cs jangan makan gaji buta,1,0,2.80.0,2025-10-29 05:42:44,"Hai kak, Mohon maaf atas ketidaknyamanannya, terkait kendala Kakak dibutuhkan pengecekan lebih lanjut oleh tim kami. Mohon kesediaannya untuk menghubungi kami melalui Chat Bantuan Ajaib pada aplikasi atau melalui email kami di support.saham@ajaib.co.id ya kak. Terima kasih ~ Rid",2025-10-29 10:23:23,2.80.0,Ajaib,ajaib.co.id,witdhraw lama saya beli token pame Whiz cuma 100rb udah 2 hari gak masuk² tolong lah bantu woi cs jangan makan gaji buta,Negative,0.990467,Trading / order execution; Customer support
17052,ba8fc685-0dd8-4627-87a1-cd66b7bfb29b,siti Rizky,https://play-lh.googleusercontent.com/a/ACg8ocJqRkoaIDw-5NRct6wwvV1NaVsdbEM7IsQ3kYC9SMwOt6GQqQ=mo,"sangat bagus,sy jdi tau tntng dunia saham",4,0,3.20.0,2026-04-23 12:27:28,"Halo kak,\n\nSenang sekali baca review positif dari Kakak. Jangan lupa rekomendasikan ke teman-teman kakak yang lain ya ☺️Jika ada saran, silakan dapat kirimkan ke kami melalui email ke support@stockbit.com atau kakak bisa klik menu Chat Support di aplikasi Stockbit.\n\nSemoga harinya menyenangkan!",2026-04-23 16:10:36,3.20.0,Stockbit,com.stockbit.android,"sangat bagus,sy jdi tau tntng dunia saham",Positive,0.992138,
18013,dc01d005-4dd8-4b1a-8e59-5c053df949d2,bunarto cen,https://play-lh.googleusercontent.com/a/ACg8ocJPZmkkDLjtTxTGp1-MGDPjNoeG6HvQ2dbK4Lwfp2_gMKTtSQ=mo,mantappp,5,0,3.20.0,2026-04-17 18:35:04,"Halo kak,\n\nSenangnya baca review positif dari Kakak. Kami akan terus berupaya untuk memberikan pengalaman yang baik untuk Kakak. Jika ada saran silakan dapat kirimkan ke kami melalui email ke support@stockbit.com atau kakak bisa klik menu Chat Support di aplikasi Stockbit.\n\nTerima kasih dan semoga hari kakak menyenangkan! ☺️\n",2026-04-20 16:14:08,3.20.0,Stockbit,com.stockbit.android,mantappp,Neutral,0.726087,
18426,d7d57bbf-74e6-48e4-bc7c-de667e6bc618,Adi Satria,https://play-lh.googleusercontent.com/a-/ALV-UjV7h-F2NCVn3bTUOflbScIw4_E6MFbk5cVGohrWD5wmIhbo2ghR,aplikasi yang sangat membantu banyak orang.fitur-fitur yang disediakan sangat mudah dan sangat membantu.informasi yang di berikan selalu update.,5,0,3.19.7,2026-04-15 20:13:15,"Halo kak,\n\nSenang sekali baca review positif dari Kakak. Jangan lupa rekomendasikan ke teman-teman kakak yang lain ya ☺️Jika ada saran, silakan dapat kirimkan ke kami melalui email ke support@stockbit.com atau kakak bisa klik menu Chat Support di aplikasi Stockbit.\n\nSemoga harinya menyenangkan!😆\n",2026-04-16 15:56:06,3.19.7,Stockbit,com.stockbit.android,aplikasi yang sangat membantu banyak orang.fitur-fitur yang disediakan sangat mudah dan sangat membantu.informasi yang di berikan selalu update.,Positive,0.997817,
11403,dcad8918-7bd4-4a26-aa18-5bd5062cab7e,Blackbyte TV,https://play-lh.googleusercontent.com/a-/ALV-UjVKnyApv7SduT0iL-uTCaLJz0ffL9N6cXcIfQOivAlVczVCAFsI,"belum pernah kasi rating bintang 1 di aplikasi, pantes rating kecil ya, data data suka dimanipulasi saham maupun crypto .. cuihhhhhh",1,3,2.93.0,2026-03-28 05:41:42,"Hi kak,mohon maaf atas kendala yang kakak alami,dapat kami informasikan bahwasannya terkait kendala kakak dibutuhkan pengecekan lebih lanjut oleh tim kami. Mohon kesediaannya untuk menghubungi kami melalui Chat Bantuan Ajaib pada aplikasi atau melalui email kami di support.saham@ajaib.co.id Terima kasih -AJ",2026-03-30 08:12:21,2.93.0,Ajaib,ajaib.co.id,"belum pernah kasi rating bintang 1 di aplikasi, pantes rating kecil ya, data data suka dimanipulasi saham maupun crypto .. cuihhhhhh",Negative,0.998543,Charts / market data
9391,0a882c19-4bc1-43d8-920b-b131cde27e39,Riski Andini,https://play-lh.googleusercontent.com/a-/ALV-UjUrJDttw4vxZ5LtI1Nq0oxBLtlebuCQLBBrYHnuKWepLvqHoVs,"sangat rempong verifikasinya. walaupun ATM sendiri harus persetujuan dri orang tua memverifikasi kk orang tua lah, KTP orang tualah. gk usah buat sistem verifikasi semacam itu cukup KTP dan kk yg ingin mrndaftar di aplikasi ini. gk usah di persulit",1,1,,2026-05-03 09:19:13,"Hi Kak, mohon maaf atas ketidaknyamanannya. Proses registrasi, verifikasi, atau pembaruan data pada kondisi tertentu memerlukan pengecekan tambahan demi keamanan akun dan kepatuhan regulasi. Ajaib terus berupaya menghadirkan onboarding yang mudah. Jika masih tertahan, hubungi Kami via Live Chat/email resmi support@ajaib.co.id. Terima kasih ~IDA",2026-05-05 16:00:36,,Ajaib,ajaib.co.id,"sangat rempong verifikasinya. walaupun ATM sendiri harus persetujuan dri orang tua memverifikasi kk orang tua lah, KTP orang tualah. gk usah buat sistem verifikasi semacam itu cukup KTP dan kk yg ingin mrndaftar di aplikasi ini. gk usah di persulit",Negative,0.933837,
17143,a3a86345-6400-4aa1-8bcd-93688b638dd9,Muhamad Suraji,https://play-lh.googleusercontent.com/a-/ALV-UjWZpHH0eg15ghktL0gVW3sWTP5NQGedXQHhn8-belrwwSjWuEuO,cocok untuk treder pemula,5,0,3.20.0,2026-04-23 12:18:09,"Halo kak,\n\nSenang sekali baca review positif dari Kakak. Jangan lupa rekomendasikan ke teman-teman kakak yang lain ya ☺️Jika ada saran, silakan dapat kirimkan ke kami melalui email ke support@stockbit.com atau kakak bisa klik menu Chat Support di aplikasi Stockbit.\n\nSemoga harinya menyenangkan!😆\n",2026-04-24 13:04:52,3.20.0,Stockbit,com.stockbit.android,cocok untuk treder pemula,Negative,0.761360,
9539,eeaa0ff4-0f4f-49d2-a34d-8aad8c81b02d,Bagas Purwo Kuncoro,https://play-lh.googleusercontent.com/a/ACg8ocJjlgLUSOaDULmQjgqKo0b2Iv9Lojo6w-ig2hZ7DY_czzHy_A=mo,"mudah digunakan, transfernya sat set ga pake lama, rekomen buat yang baru belajar investasi",5,0,2.95.0,2026-04-28 08:09:10,"Terima kasih banyak, Kak! ⭐⭐⭐⭐⭐ Dukungan Kakak sangat berarti buat tim Ajaib. Semangat terus invest-nya ya! 💙 ~YOH",2026-05-18 12:46:47,2.95.0,Ajaib,ajaib.co.id,"mudah digunakan, transfernya sat set ga pake lama, rekomen buat yang baru belajar investasi",Positive,0.922086,
11799,587c256b-d0aa-4db3-9cb3-a845f8974fc0,successfully30,https://play-lh.googleusercontent.com/a-/ALV-UjWni9vBQX03tBY9q5aBGgaijuqm6EnA6Yc7jTQ7m3UR_qpO4mih,jelek banget aplikasi nya lelet lemot proses nya lama udh telat dikit ilang duit ilang peluang. proses kirim usdt juga lama kecewa banget,1,2,2.91.1,2026-02-28 23:00:25,"Hi kak,mohon maaf atas kendal yang kakak alami,dapat kami informasikan bahwasannya terkait kendala kakak dibutuhkan pengecekan lebih lanjut oleh tim kami. Mohon kesediaannya untuk menghubungi kami melalui Chat Bantuan Ajaib pada aplikasi atau melalui email kami di support.saham@ajaib.co.id Terima kasih -AJ\n",2026-03-02 08:32:40,2.91.1,Ajaib,ajaib.co.id,jelek banget aplikasi nya lelet lemot proses nya lama udh telat dikit ilang duit ilang peluang. proses kirim usdt juga lama kecewa banget,Negative,0.999435,App stability / speed
10289,846d55a8-5c6b-4090-aebc-d11b82e2b007,zico Argenxer,https://play-lh.googleusercontent.com/a-/ALV-UjUSjHu1_0EiUqu27x4RnnR8nMZkWtG1zrsh93-Pmgl5LNDjNjls,terimakasih ajaib sudah memudahkan untuk berinvestasi,5,0,2.80.0,2026-04-18 09:19:28,"Hi Investor Ajaib, terima kasih atas apresiasinya, kami berkomitmen untuk terus meningkatkan kualitas produk dan layanan yang kami miliki. Terima kasih telah menjadi pelanggan setia Ajaib! ~ADI",2026-04-27 11:40:13,2.80.0,Ajaib,ajaib.co.id,terimakasih ajaib sudah memudahkan untuk berinvestasi,Neutral,0.717969,

In [10]:
# Hanya review dengan label Positive atau Negative
df_polar = df_sentiment[
    df_sentiment["Text_Sentiment"].isin(["Positive", "Negative"])
].copy()

table = pd.crosstab(
    df_polar["Competitor"],
    df_polar["Text_Sentiment"]
).reindex(columns=["Positive", "Negative"], fill_value=0)

table_pct = (
    table.div(table.sum(axis=1), axis=0) * 100
).round(1)

display(table_pct)

Text_Sentiment          Positive  Negative
Competitor
Ajaib                       70.3      29.7
IPOT                        44.9      55.1
KISI (KOINS Mobile)         31.2      68.8
KISI (iKISI)                73.3      26.7
Mirae Asset (Neo HOTS)      12.3      87.7
Stockbit                    55.3      44.7

In [12]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [13]:
print(CHECK_FILE.resolve())

D:\KISI_Competitor_Analysis\RoBERTa_Manual_Check.xlsx

In [14]:
from pathlib import Path
import re
import pandas as pd
import torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm import tqdm

# =========================================================
# 1. FILE DAN PENGATURAN
# =========================================================
FOLDER = Path(r"D:\KISI_Competitor_Analysis")
INPUT_FILE = FOLDER / "google_play_roberta_detail.csv"

MODEL_NAME = "w11wo/indonesian-roberta-base-sentiment-classifier"
BATCH_SIZE = 16

if not INPUT_FILE.exists():
    raise FileNotFoundError(f"File tidak ditemukan: {INPUT_FILE}")

df = pd.read_csv(INPUT_FILE, keep_default_na=False)

if "Competitor" not in df.columns:
    raise ValueError("Kolom Competitor tidak ditemukan.")

text_column = (
    "Review_Text" if "Review_Text" in df.columns else "content"
)

if text_column not in df.columns:
    raise ValueError("Kolom Review_Text atau content tidak ditemukan.")

df["Review_Text"] = df[text_column].astype(str).str.strip()

# Simpan hasil sebelumnya untuk dibandingkan
if "Text_Sentiment" in df.columns:
    df["Previous_Sentiment"] = df["Text_Sentiment"]

# =========================================================
# 2. NORMALISASI EJAAN
#    Teks asli tetap disimpan.
#    Negasi seperti "tidak", "gak", dan "belum" tidak dihapus.
# =========================================================
REPLACEMENTS = {
    "mantaf": "mantap",
    "mantaap": "mantap",
    "mantappp": "mantap",
    "mantapppp": "mantap",
    "treder": "trader",
    "pasword": "password",
    "witdhraw": "withdraw",
    "withdrawl": "withdraw",
    "gabisa": "tidak bisa",
    "gak": "tidak",
    "nggak": "tidak",
    "gk": "tidak",
    "ga": "tidak",
    "tp": "tapi",
    "tdk": "tidak",
    "udh": "sudah",
    "sdh": "sudah",
    "sy": "saya",
    "apk": "aplikasi",
    "tntng": "tentang",
}

def normalize_text(text):
    text = str(text).lower().strip()

    # Batasi pengulangan berlebihan: baguuuus → baguus.
    # Hindari menghapus semua pengulangan huruf.
    text = re.sub(r"([a-z])\1{2,}", r"\1\1", text)

    # Beberapa bentuk pujian informal yang umum
    text = re.sub(r"\bmanta+p+\b", "mantap", text)
    text = re.sub(r"\bbagu+s+\b", "bagus", text)

    for original, replacement in REPLACEMENTS.items():
        text = re.sub(
            rf"\b{re.escape(original)}\b",
            replacement,
            text,
        )

    return re.sub(r"\s+", " ", text).strip()

df["Normalized_Text"] = df["Review_Text"].map(normalize_text)

print(f"Jumlah review: {len(df):,}")
print(
    "Teks yang berubah:",
    df["Review_Text"].str.lower().ne(df["Normalized_Text"]).sum(),
)

# =========================================================
# 3. MUAT MODEL ROBERTA
# =========================================================
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)

model.to("cpu")
model.eval()

labels = {
    int(key): str(value).lower()
    for key, value in model.config.id2label.items()
}

if set(labels.values()) != {"positive", "neutral", "negative"}:
    raise ValueError(f"Label model tidak sesuai: {labels}")

print("Model labels:", labels)

# =========================================================
# 4. ANALISIS SENTIMEN
#    Analisis teks unik, lalu kembalikan ke seluruh review.
#    Tidak memakai rating bintang sebagai input.
# =========================================================
unique_texts = (
    df.loc[df["Normalized_Text"].ne(""), "Normalized_Text"]
    .drop_duplicates()
    .tolist()
)

prediction_map = {}

for start in tqdm(
    range(0, len(unique_texts), BATCH_SIZE),
    desc="Analyzing sentiment",
):
    batch = unique_texts[start:start + BATCH_SIZE]

    inputs = tokenizer(
        batch,
        padding=True,
        truncation=True,
        max_length=512,
        return_tensors="pt",
    )

    with torch.inference_mode():
        logits = model(**inputs).logits
        probabilities = torch.softmax(logits, dim=-1)

    # tolist() tidak memerlukan konversi tensor ke NumPy
    for text, probs in zip(batch, probabilities.tolist()):
        best_id = max(range(len(probs)), key=lambda i: probs[i])

        prediction_map[text] = {
            "Sentiment": labels[best_id].capitalize(),
            "Score": probs[best_id],
        }

df["Text_Sentiment"] = df["Normalized_Text"].map(
    lambda text: prediction_map[text]["Sentiment"]
    if text in prediction_map else "Not analyzed"
)

df["Model_Score"] = df["Normalized_Text"].map(
    lambda text: prediction_map[text]["Score"]
    if text in prediction_map else None
)

# Simpan segera agar hasil analisis tidak hilang
df.to_csv(
    FOLDER / "google_play_roberta_normalized_detail.csv",
    index=False,
    encoding="utf-8-sig",
)

# =========================================================
# 5. TEMA KELUHAN BERDASARKAN KATA KUNCI
#    Hanya diterapkan pada review yang diprediksi Negative.
# =========================================================
THEMES = {
    "Login / account access": [
        r"\blog[\s-]?in\b", r"\bpassword\b",
        r"\bsandi\b", r"\botp\b", r"\bmasuk akun\b",
    ],
    "Registration / verification": [
        r"\bverifikasi\w*\b", r"\bverif\b",
        r"\bregistrasi\b", r"\bpendaftaran\b",
        r"\bdaftar\b", r"\bbuka akun\b", r"\bktp\b",
    ],
    "Deposit / withdrawal": [
        r"\bdeposit\b", r"\btop[\s-]?up\b",
        r"\bwithdraw\w*\b", r"\bwd\b",
        r"\bpenarikan\b", r"\btarik (?:saldo|dana|uang)\b",
        r"\btransfer\b", r"\bsetor\w*\b",
    ],
    "App stability / speed": [
        r"\bbug\w*\b", r"\ber+r?o+r+\w*\b",
        r"\bcrash\w*\b", r"\blemot\b", r"\blelet\b",
        r"\blambat\b", r"\blag\b", r"\bnge(?:lag|leg)\w*\b",
        r"\bloading\b", r"\bhang\b", r"\bforce close\b",
        r"\btidak\s+(?:bisa\s+)?(?:di\s*)?buka\b",
    ],
    "Trading / order execution": [
        r"\border\b", r"\bauto[\s-]?order\b",
        r"\bstop[\s-]?loss\b", r"\bjual\b", r"\bbeli\b",
        r"\beksekusi\b", r"\bmatched\b", r"\breject\w*\b",
    ],
    "Charts / market data": [
        r"\bchart\w*\b", r"\bgrafik\b", r"\bcandle\w*\b",
        r"\border[\s-]?book\b", r"\bdata saham\b",
        r"\bdata harga\b", r"\breal[\s-]?time\b",
    ],
    "Fees / charges": [
        r"\bfee\b", r"\bbiaya\b", r"\bkomisi\b",
        r"\bpotongan\b", r"\btarif\b",
    ],
    "Customer support": [
        r"\bcs\b", r"\bcustomer (?:service|support)\b",
        r"\blayanan pelanggan\b", r"\blive chat\b",
        r"\bchat bantuan\b", r"\badmin\b",
        r"\brespon\w*\b",
    ],
}

def detect_themes(text):
    matches = [
        theme
        for theme, patterns in THEMES.items()
        if any(re.search(pattern, text) for pattern in patterns)
    ]
    return "; ".join(matches) if matches else "Other / unclear"

df["Complaint_Themes"] = [
    detect_themes(text) if sentiment == "Negative" else ""
    for text, sentiment in zip(
        df["Normalized_Text"], df["Text_Sentiment"]
    )
]

# =========================================================
# 6. TABEL SENTIMEN
# =========================================================
analyzed = df[df["Text_Sentiment"].ne("Not analyzed")].copy()
label_order = ["Positive", "Neutral", "Negative"]

counts = pd.crosstab(
    analyzed["Competitor"], analyzed["Text_Sentiment"]
).reindex(columns=label_order, fill_value=0)

summary = counts.copy()
summary["Texts Analyzed"] = counts.sum(axis=1)

for label in label_order:
    summary[f"{label} %"] = (
        counts[label] / summary["Texts Analyzed"] * 100
    ).round(1)

summary["Reviews Collected"] = (
    df.groupby("Competitor").size().reindex(summary.index)
)

if "score" in df.columns:
    df["score"] = pd.to_numeric(df["score"], errors="coerce")
    summary["Avg Review Rating"] = (
        df.groupby("Competitor")["score"].mean().round(2)
    )

# =========================================================
# 7. HITUNG THEME MENTIONS
#    Satu review dihitung sekali untuk setiap tema.
# =========================================================
negative = analyzed[
    analyzed["Text_Sentiment"].eq("Negative")
].copy()

theme_rows = negative.assign(
    Theme=negative["Complaint_Themes"].str.split(";")
).explode("Theme")

theme_rows["Theme"] = theme_rows["Theme"].str.strip()
theme_rows = (
    theme_rows.reset_index(names="Review_Row")
    .drop_duplicates(["Review_Row", "Theme"])
)

theme_counts = (
    theme_rows.groupby(["Competitor", "Theme"])
    .size()
    .reset_index(name="Theme Mentions")
)

summary["Top Complaint Theme"] = "No specific theme detected"
summary["Theme Mentions"] = 0

for competitor in summary.index:
    specific = theme_counts[
        theme_counts["Competitor"].eq(competitor)
        & theme_counts["Theme"].ne("Other / unclear")
    ]

    if not specific.empty:
        maximum = specific["Theme Mentions"].max()
        top = specific[specific["Theme Mentions"].eq(maximum)]

        summary.loc[competitor, "Top Complaint Theme"] = (
            "; ".join(sorted(top["Theme"].tolist()))
        )
        summary.loc[competitor, "Theme Mentions"] = int(maximum)

summary["Status"] = "Normalized RoBERTa — not manually validated"

summary = summary.reset_index()
summary.columns.name = None

ppt_columns = [
    "Competitor", "Reviews Collected", "Texts Analyzed",
]

if "Avg Review Rating" in summary.columns:
    ppt_columns.append("Avg Review Rating")

ppt_columns += [
    "Positive %", "Neutral %", "Negative %",
    "Top Complaint Theme", "Theme Mentions", "Status",
]

ppt_table = summary[ppt_columns]

# =========================================================
# 8. TAMPILKAN DAN SIMPAN
# =========================================================
display(ppt_table)

df.to_csv(
    FOLDER / "google_play_roberta_normalized_detail.csv",
    index=False,
    encoding="utf-8-sig",
)

ppt_table.to_csv(
    FOLDER / "google_play_roberta_normalized_summary.csv",
    index=False,
    encoding="utf-8-sig",
)

# Sampel pemeriksaan: maksimal 10 review per label per aplikasi
sample_parts = [
    group.sample(n=min(10, len(group)), random_state=42)
    for _, group in analyzed.groupby(
        ["Competitor", "Text_Sentiment"]
    )
]

validation_sample = (
    pd.concat(sample_parts, ignore_index=True)
    if sample_parts else analyzed.copy()
)

validation_sample["Manual_Sentiment"] = ""
validation_sample["Validation_Notes"] = ""

# Nama baru setiap ekspor agar tidak menimpa pemeriksaan lama
timestamp = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")
output_file = FOLDER / f"KISI_RoBERTa_Normalized_{timestamp}.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    ppt_table.to_excel(writer, sheet_name="PPT_Summary", index=False)
    theme_counts.to_excel(writer, sheet_name="All_Themes", index=False)
    df.to_excel(writer, sheet_name="Review_Details", index=False)
    validation_sample.to_excel(
        writer, sheet_name="Validation_Sample", index=False
    )

print("Excel tersimpan:", output_file)

if "Previous_Sentiment" in df.columns:
    changed = (
        df["Previous_Sentiment"].astype(str).str.capitalize()
        .ne(df["Text_Sentiment"])
        & df["Text_Sentiment"].ne("Not analyzed")
    )
    print("Label berbeda dari hasil sebelumnya:", changed.sum())

Jumlah review: 23,394
Teks yang berubah: 4657

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 547.24it/s]

Model labels: {0: 'positive', 1: 'neutral', 2: 'negative'}

Analyzing sentiment: 100%|██████████| 1257/1257 [12:17<00:00,  1.71it/s]

,Competitor,Reviews Collected,Texts Analyzed,Avg Review Rating,Positive %,Neutral %,Negative %,Top Complaint Theme,Theme Mentions,Status
0,Ajaib,15557,15557,4.22,63.9,9.5,26.7,App stability / speed,657,Normalized RoBERTa — not manually validated
1,IPOT,1631,1631,3.31,41.4,7.4,51.2,App stability / speed,212,Normalized RoBERTa — not manually validated
2,KISI (KOINS Mobile),19,19,2.84,21.1,10.5,68.4,App stability / speed,8,Normalized RoBERTa — not manually validated
3,KISI (iKISI),131,131,4.18,65.6,11.5,22.9,Registration / verification,7,Normalized RoBERTa — not manually validated
4,Mirae Asset (Neo HOTS),116,116,1.97,12.1,10.3,77.6,Login / account access,39,Normalized RoBERTa — not manually validated
5,Stockbit,5940,5940,3.91,49.1,11.9,39.1,App stability / speed,753,Normalized RoBERTa — not manually validated

Excel tersimpan: D:\KISI_Competitor_Analysis\KISI_RoBERTa_Normalized_20261006_115908.xlsx
Label berbeda dari hasil sebelumnya: 597

In [15]:
from pathlib import Path
import pandas as pd

folder = Path(r"D:\KISI_Competitor_Analysis")
file = folder / "google_play_roberta_normalized_detail.csv"

df = pd.read_csv(file, keep_default_na=False)

apps = [
    "KISI (iKISI)",
    "KISI (KOINS Mobile)",
    "Stockbit",
    "Ajaib",
]

selected = df[
    df["Competitor"].isin(apps)
    & df["Review_Text"].astype(str).str.strip().ne("")
].drop_duplicates(["Competitor", "Review_Text"])

samples = []

for app in apps:
    for sentiment in ["Positive", "Negative"]:
        group = selected[
            selected["Competitor"].eq(app)
            & selected["Text_Sentiment"].eq(sentiment)
        ]

        if not group.empty:
            samples.append(
                group.sample(n=min(2, len(group)), random_state=42)
            )

if not samples:
    raise ValueError("Tidak ada review yang sesuai ditemukan.")

result = pd.concat(samples, ignore_index=True)

columns = ["Competitor", "Text_Sentiment", "Review_Text"]
if "score" in result.columns:
    columns.append("score")

result = result[columns].rename(columns={
    "Competitor": "App",
    "Text_Sentiment": "RoBERTa Label",
    "Review_Text": "Review",
    "score": "Stars",
})

pd.set_option("display.max_colwidth", None)
display(result)

,App,RoBERTa Label,Review,Stars
0,KISI (iKISI),Positive,aplikasi nya bagus banget dan mudah di pahami untuk pemula,5
1,KISI (iKISI),Positive,"Semua OK dari segi tampilan, performa dan layanan. 👍",5
2,KISI (iKISI),Negative,trading balance gak bisa ditarik..ada saldonya tapi di menu penarikan saldo tersedia selalu 0..payah,1
3,KISI (iKISI),Negative,daftar ya susah gimna ij cara daftar ia,2
4,KISI (KOINS Mobile),Positive,apk paling okk,5
5,KISI (KOINS Mobile),Positive,"belajar saham dari kisi semarang dan ngerti saham. dari tidak tau menjadi tahu, belajar saham untuk pemula bersama kisi semarang dengan ngerti saham",5
6,KISI (KOINS Mobile),Negative,"kenapa withdrawl ke rekening pribadi lama sekali?? padahal dari jam 08:00 wib, sampai jam 14:30 belum masuk, lagi perlu uang",3
7,KISI (KOINS Mobile),Negative,skrg jd suka eror,1
8,Stockbit,Positive,"bagus fiturnya banyak dan mudah dimengerti juga,tapi kendala nya kalo mau wd suka lama banget nunggu dari pagi blom juga masuk",4
9,Stockbit,Positive,Sangat bagus untuk investasi terutama bagi pemula,5
10,Stockbit,Negative,"aplikasinya bagus, cs nya mau respon retail retail kecil ini",5
11,Stockbit,Negative,"Hari² eror mulu setiap pasar buka hadeh stockbit ,minimal.diperbaikin lah masak eror mulu",3
12,Ajaib,Positive,sangat memuaskan dan investasi di ajaib mudah dan terpercaya,5
13,Ajaib,Positive,salah satu aplikasi terbaik untuk investasi jangka panjang,5
14,Ajaib,Negative,lambat,1
15,Ajaib,Negative,aplikasi apaan nih lemot csnya lemot aplikasi kurang rekomendet buat di install aku ngga papa kok di blokir sementara mana 3 hari lagi,1

In [16]:
from pathlib import Path
from io import StringIO
import pandas as pd

file = Path(r"D:\KISI_Competitor_Analysis\multiTimeline (9).csv")

if not file.exists():
    raise FileNotFoundError(f"File tidak ditemukan: {file}")

# Cari baris header karena CSV Trends punya keterangan di awal
lines = file.read_text(encoding="utf-8-sig").splitlines()

header_row = next(
    (
        i for i, line in enumerate(lines)
        if line.split(",")[0].strip().strip('"')
        in ["Week", "Day", "Month", "Minggu", "Hari", "Bulan"]
    ),
    None,
)

if header_row is None:
    print("\n".join(lines[:10]))
    raise ValueError("Header belum dikenali. Kirim output di atas.")

df_trends = pd.read_csv(
    StringIO("\n".join(lines[header_row:]))
)

print("Kolom:", df_trends.columns.tolist())
print("Jumlah baris:", len(df_trends))
display(df_trends.head())

Kolom: ['Week', 'ikisi: (Indonesia)', 'stockbit: (Indonesia)', 'mirae: (Indonesia)', 'ajaib: (Indonesia)', 'IPOT: (Indonesia)']
Jumlah baris: 53

,Week,ikisi: (Indonesia),stockbit: (Indonesia),mirae: (Indonesia),ajaib: (Indonesia),IPOT: (Indonesia)
0,2025-10-05,0,60,9,56,14
1,2025-10-12,0,56,7,55,13
2,2025-10-19,0,49,7,49,12
3,2025-10-26,0,49,8,51,12
4,2025-11-02,0,56,10,51,12